### ISSUE TITLE
Build and Release Automation

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/dba-dash#10]

**Comment by jeffdoolittle** [comment]
@DavidWiseman with your latest changes that got the build working, how close are you to being able to generate the zip artifacts automatically?

**Comment by DavidWiseman** [comment]
@jeffdoolittle I'm almost there.  It currently works like this:

* You create a tag and push the changes.  
* The workflow will build the project. 
* A separate zip is created for the Agent+GUI and the GUI only.  e.g. DBADash_2.11.1.zip, DBADash_GUIOnly_2.11.1.zip
* A release is created with the zip files attached - in draft mode.

Just need to do a bit more testing before I create a PR for it.  I might change the versioning from the .NET side to remove the automated build/revision and set manually.   Then enable deterministic builds and stick with Major.Minor.Revision.  This is all set from GlobalAssemblyInfo.cs.  The DB project is controlled separately.

**Comment by jeffdoolittle** [comment]
It looks great to me! Is your intention to have the tag-create-release always make a draft, or were you just testing for now? just curious.

Great work! So awesome to see the continued innovation.

**Comment by DavidWiseman** [comment]
Thanks @jeffdoolittle.  I think a draft works best for now - still allowing for some manual control over the process.  I can deploy the new release internally before making it public.  I'd like to do a bit more with github actions -automated testing beyond checking if the project builds would be good.

**Comment by jeffdoolittle** [comment]
Absolutely, the more automation the better!
