### ISSUE TITLE
Last Good CheckDB on tempdb

### ISSUE THREAD

**Issue by AlreadyPicked** [trimble-oss/dba-dash#1026]
I get a critical error on all my instances because we never do any checkdb on tempdb. We use Ola Hallengren's scripts for maintenance and it skips tempdb.

Maybe add a setting to the service to skip that?

**Comment by DavidWiseman** [comment]
On the Last Good CheckDB tab, click the gear icon and select "Configure Root Thresholds".  Enter "tempdb" into the Excluded DBs checkbox (comma separated if you have other DBs to exclude).  This will now be excluded across all instances. 
The threshold can also be updated at the instance and database level but the root level is the easiest option to exclude tempdb for all your instances.

Hope this helps

**Comment by AlreadyPicked** [comment]
Oh I missed those filters. Sorry.

Thansk for the quick reply.
