### ISSUE TITLE
Exception on drivers tab on the main configuration report 

### ISSUE THREAD

**Issue by vitorfavamastery** [trimble-oss/dba-dash#1030]
I using DBA Dash to monitor 833 SQL Instances and when I try to open the Driver tab on the main configuration for all the SQL Server instances there is an Exception error:

"Sum of the columns FillWeight values cannot exceed 65535

![image](https://github.com/user-attachments/assets/64ab24cd-7012-400f-ace6-0289eeeecf80)

**Comment by DavidWiseman** [comment]
Hi, thanks for reporting this.  Can you copy/paste the full error text from the dialog? It will help narrow things down.  Also, can you tell me how many SQL instances you are monitoring?  Just wondering if this might be a factor with it creating a column per instance.

**Comment by DavidWiseman** [comment]
This will be fixed in the _next_ release (soon).  The tab might be slow to load with over 653 SQL Instances but you will no longer get this error.  
As a workaround you can use the grouping and filtering options to limit the number of SQL instances

**Comment by vitorfavamastery** [comment]
[celebrate]     Vitor Fava (EXT) reacted to your message:

Vitor Fava (EXT)
Senior Database Developer
Mastery Logistics Systems, Inc.
Email: 
***@***.***
www.mastery.net
________________________________

**Comment by DavidWiseman** [comment]
Fixed in 3.11 🚀
