### ISSUE TITLE
Errors manually triggering collection for Snapshot Summary

### ISSUE THREAD

**Issue by tdinh2011** [trimble-oss/dba-dash#1034]
I get this error when manually triggering a collection for a snapshot summary. Clicking on Continue and restarting the app did not fix the issue.
![image](https://github.com/user-attachments/assets/b0836d66-eb1b-4581-a0e3-ea991e967b7f)

**Comment by DavidWiseman** [comment]
Thanks for reporting this.  It will be fixed in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 3.11 🚀
