### ISSUE TITLE
SQL language

### ISSUE THREAD

**Issue by zaffinger** [trimble-oss/dba-dash#104]
hi,

if the default language of the user is NOT english_us you get following error:
```
SqlProcedure "[dbo].[VLF_Upd]" wird erstellt...
SqlProcedure "[dbo].[Waits_Get]" wird erstellt...
SqlProcedure "[dbo].[Waits_Upd]" wird erstellt...
Msg 4132, Level 16, State 1, Procedure Waits_Upd, Line 72 [Batch Start Line 21429]
Der für die @MaxDate-Variable in der OPTIMIZE FOR-Klausel angegebene Wert konnte nicht implizit in den Typ dieser Variablen konvertiert werden.
** An error was encountered during execution of batch. Exiting.

Completion time: 2022-03-21T14:06:10.1855006+01:00
```

I added:

SET LANGUAGE us_english;

```
GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;

SET LANGUAGE us_english;
```

**Comment by DavidWiseman** [comment]
It looks like the issue might be related to the string literal format used for dates.  Changing to a format that works across languages should fix this issue - this is something I can take a look at.

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms180878(v=sql.105)?redirectedfrom=MSDN
https://dba.stackexchange.com/questions/166771/what-date-time-literal-formats-are-language-and-dateformat-safe

```sql
DECLARE @d VARCHAR(20) = '9999-12-31' -- depends on language 

-- fails
SET LANGUAGE français;
SELECT CAST(@d AS DATETIME)

-- succeeds
SET LANGUAGE us_english;
SELECT CAST(@d AS DATETIME)

SET @d = '99991231' --  format works accross languages

-- succeeds
SET LANGUAGE français;
SELECT CAST(@d AS DATETIME)

-- succeeds
SET LANGUAGE us_english;
SELECT CAST(@d AS DATETIME)
```

**Comment by DavidWiseman** [comment]
Fixes were only required in two places in the app.  This will be included in the next release.

**Comment by DavidWiseman** [comment]
This issue is fixed in the latest release now.
