### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by Jhn007** [trimble-oss/dba-dash#1040]
Morning David,

Firstly would like to say that have been using DBADash for approx 1 yer now and think it is fantastic. 

I have attempted to upgrade from 3.0.1.0 to 3.11.0.0 today (admittedly I am behind on the version updates!) but have encountered an issue during the DB upgrade. Which I guess could be because I am behind in updating our version of the app.

The DB Repository is on SQL Server 2019
The DBADash application is running on Windows Server 2019 

The error I get in the logs is below if you could let me know how to get past this then it would be much appreciated 

Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 4922, Level 16, State 9, Line 1 ALTER TABLE DROP COLUMN InstanceDisplayName failed because one or more objects access this column.
Error SQL72045: Script execution error.  The executed script:
ALTER TABLE [dbo].[Instances] DROP COLUMN [InstanceDisplayName], COLUMN [InstanceGroupName], COLUMN [LastMemoryDumpUTC];

**Comment by DavidWiseman** [comment]
Hi,

How did you upgrade the database - did you generate a script and run it in SSMS or did you let it run the deployment using the Deploy button or just run automatically on startup?  If you generated a script, try letting it deploy automatically instead.

Hope this helps,

David

**Comment by Jhn007** [comment]
That was a quick response! 

Deployed using the the ServiceConfigTool and letting it run automatically on startup of the service. Is an offline upgrade so I had manually downloaded the latest release, copied and extracted to the serverr, keeping a copy of the original ServiceConfig.json file as per the manual upgrade instructions

**Comment by DavidWiseman** [comment]
Run this on the repository database first:

`DROP INDEX IX_Instances_InstanceDisplayName ON dbo.Instances`

**Comment by Jhn007** [comment]
That has worked many thanks

**Comment by DavidWiseman** [comment]
Some more info:

The issue occurs when upgrading from version 3.3.0 or lower to version 3.11.0. Version 3.4.0 and later will upgrade to 3.11.0 without issues.  
The easiest option is to drop the index that is preventing the upgrade.  Or upgrading to version 3.4-3.10 then to 3.11 should work.

```sql
DROP INDEX IX_Instances_InstanceDisplayName ON dbo.Instances
```

It should get handled automatically by the dacpac deployment but it's not generating the upgrade script correctly for some reason.  

I've put a notice on the release notes.

**Comment by DavidWiseman** [comment]
3.11.1 fixes this issue for people upgrading from older versions
