### ISSUE TITLE
Built In SA Report

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#1055]
Can we have Built in SA report right under the Service Account Report you have added to the latest build. 

It would be a great feature to see which accounts have SA rights. We use tempSA access a lot to get things done and then expire it. 

Having a report that who has SA and for how many days if possible that would be great.

**Comment by DavidWiseman** [comment]
Hi, the data is already collected for this.  If you run the script attached to this discussion #1018 it will create a custom report for you.  Note: The history isn't tracked so it's not possible to see how long someone has had the sysadmin role for.

**Comment by aachaemenes** [comment]
can you make it as build in with the next release? I think it is really valuable. Just a suggestion.

**Comment by DavidWiseman** [comment]
This will be included in the next release.

**Comment by DavidWiseman** [comment]
Included in 3.12 🚀
