### ISSUE TITLE
SQL Errorlog Viewer 

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#1064]
Adding ability to dbadash to monitor or view SQL error log.

**Comment by DavidWiseman** [comment]
Similar to #1062, maybe sp_LogHunter could be triggered to run on demand.  

The problem with collecting data from the error log is the signal-to-noise ratio.  Filtering out known noise is one option but seems like a losing battle to create a universal exclusion list (I've gone down this route in the past and abandoned it).  Filtering for known interesting events might be a better approach - I think sp_LogHunter might do this.  

Interrogating the error log from DBA Dash would be useful.  I think this could be done directly with the [messaging](https://dbadash.com/docs/help/messaging/) feature.  It's not on my immediate radar, but I'd like to include it at some point.
