### ISSUE TITLE
Is there an anlternative way to get the feature "Community Tools" working?

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#1107]
Hi,

DBADash Version in Use: 3.13.0.0

I was going to set up and use the new feature "Community Tools" and I discovered that the provided method is only for DBATools and PowerShell (https://dbadash.com/docs/help/community-tools/). I already have all the community tools listed installed on my servers and I maintain them manually and they are not installed on master database! I am also not using the DBATools. 

So I was wondering if there is an anlternative way to get the feature "Community Tools" working. The DBADash Service User I have in use does not need any GRANTs either as it is a memeber of sysadmin.

**Comment by DavidWiseman** [comment]
Any other method of deployment is fine and the grants are not required if the service account is sysadmin.

Usually I would avoid putting anything in the master database, but it makes sense for the community scripts IMO.  One of the advantages of deploying to master is that they can be executed from any database.  If you deploy to a different database, they need to be executed from that database.  If you still prefer not to deploy anything to master that's also totally reasonable - we just need to ensure that DBA Dash is connecting to the database where the tools are deployed.

It's likely that DBA Dash is connecting to the master database where it's trying to run the community scripts and not finding them.  If you change the Initial Catalog in the connection string to the database where they are deployed it should work. Or the initial catalog can be omitted and the service account's default database changed instead.

Hope this helps.
