### ISSUE TITLE
Cannot collect Drives and ServerExtraProperties

### ISSUE THREAD

**Issue by dmartesi** [trimble-oss/dba-dash#111]
Hi, as stated in the title I'm not able to collect some information with DBADash.
Except these few errors, everything else works as expected.

Here are my problems:
**1. Drives**
Error message
System.UnauthorizedAccessException: Access Denied.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at DBADash.DBCollector.collectDrivesWMI() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1378

**2. ServerExtraProperties**
Error message
System.UnauthorizedAccessException: Access Denied.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at DBADash.DBCollector.collectComputerSystemWMI() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1155

I've created a new account for DBADash service.
This new account is part of Windows Administrators group on the machine where DBADash is installed; the account is part of Windows Administrators group and SQL Server Sysadmins group on the managed instance.

Can you help me understand what's going wrong?

Thanks

David

**Comment by DavidWiseman** [comment]
Hi,

It looks like DBA Dash is having problems collecting data via Windows Management Instruction (WMI).  Most of the data DBA Dash collects is via SQL queries.  The data it's trying to collect via WMI is drive space information & some OS information like power plans, manufacturer, model etc.  For the most part this data will be collected via these queries if WMI isn't available so you don't lose too much without WMI:

https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLDrives.sql
https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLServerExtraProperties.sql

If you want to disable WMI to avoid these errors you can open the service configuration tool.  In the "Source" tab check "No WMI" for each instance you want to disable it for.

You might find that you are missing drive space data for any volumes that don't have SQL files without WMI though.  If you want to troubleshoot WMI, you could test to see if it's working via powershell with this user account:
https://docs.microsoft.com/en-us/windows/win32/wmisdk/connecting-to-wmi-on-a-remote-computer-by-using-powershell

Hope this helps,

David

**Comment by dmartesi** [comment]
Hi David,
finally I got it!

I tested access via Powershell and I was not able to connect.
I found the solution here: https://martellotech.com/blog/enable-remote-wmi-access-for-a-domain-user-account/
I've added DBA Dash service account to "Performance Log Users" group on the managed instance, then grant DBA Dash service account access to WMI.

Thanks for the support

**Comment by DavidWiseman** [comment]
Great!  Thank you for posting back to let me know.  I might look at updating the documentation - maybe with a link to that URL.

**Comment by dmartesi** [comment]
Hi David,
I have another error... the source is Drivers:
System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name)
   at DBADash.DBCollector.collectDriversWMI() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1328

I think DBA Dash service account another needs some other permissions.
Can you tell me what is DBA Dash trying to collect?

Thanks

**Comment by DavidWiseman** [comment]
Hi,

It's this line of code that is failing:
````C#
var PVKey = RegistryKey.OpenRemoteBaseKey(RegistryHive.LocalMachine, computerName, RegistryView.Registry64).OpenSubKey("SOFTWARE\\Amazon\\PVDriver");
````

https://github.com/trimble-oss/dba-dash/blob/main/DBADash/DBCollector.cs

I added driver collection to DBA Dash mostly because I wanted to check that my AWS drivers are up to date.  e.g. PV Driver, ENA, NVMe.  Mostly the driver information is collected via WMI but in this case I need to read a registry key to get the PV driver version.  Outside of AWS, this call will return null where the registry key doesn't exist and this would be handled without errors. It looks like there is a permissions issue reading the registry key - the service account will need access to read this key.

This data is only collected once a day by default (or on service start) as driver information shouldn't change very frequently.  If you are not interested in collecting driver versions it's possible to disable this collection.  In the service config tool click "Configure Schedule" under the "Options" tab.  Look for DriversWMI collection type.  Uncheck Default & Run on service start.  Replace the schedule cron expression with a blank string.  

Hope this helps,

David

**Comment by dmartesi** [comment]
Hi David,
I've disabled DriversWMI collection but when service starts, the same error is generated.

![2022-03-30 10_42_07-DBA Dash - SRV-DB](https://user-images.githubusercontent.com/102602420/160789916-77f6c8fe-6d29-49a1-b826-9cfecf091ee2.png)

Am I missing something?

Thanks
