### ISSUE TITLE
sp_HumanEventsBlockViewer to be added to community Tool

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#1113]
Please add sp_HumanEventsBlockViewer to the community Tool.

Also the parameters for each community tool are not preserved when you click on some different section and go back. You need to set parameters again for your run. It would be nice to be able to set some parameters globally as defaults for all servers.

**Comment by aachaemenes** [comment]
Thanks a lot. The view is really helpful.

**Comment by DavidWiseman** [comment]
To be included in the next release. 🎉

**Comment by DavidWiseman** [comment]
Included in 3.14 🚀
