### ISSUE TITLE
Feature Request: Add option Use Dual Event Session and Persist XE Sessions in dbadashconfig command line tool

### ISSUE THREAD

**Issue by tvanzeleDelen** [trimble-oss/dba-dash#1127]
Hi, 

It seems that the options for 'Use Dual Event Session' and 'Persist XE Sessions' are missing when adding sources via the dbadashconfig command line tool.
Is it possible to add these please?

Thx

**Comment by DavidWiseman** [comment]
Thanks for the suggestion, I'll probably add this in a future release.

**Comment by DavidWiseman** [comment]
This will be included in the next release. 🚀

**Comment by DavidWiseman** [comment]
Included in 3.15 🎉
