### ISSUE TITLE
Feature Request: 2 possible useful Community Tools which could be added to the current collection

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#1129]
Hi,

I do use very often these 2 scripts which are from Kenneth Fisher, "http://www.sqlstudies.com", 

1. https://github.com/sqlstudent144/SQL-Server-Scripts/blob/main/sp_SrvPermissions.sql
2. https://github.com/sqlstudent144/SQL-Server-Scripts/blob/master/sp_DBPermissions.sql

maybe you could consider implementing them into the Community Tools Collection

**Comment by DavidWiseman** [comment]
To be included in the next release. 🚀
