### ISSUE TITLE
Many DBA Dash errors in Tool

### ISSUE THREAD

**Issue by chaithanyagade** [trimble-oss/dba-dash#1147]
I could see many Primary key violation errors form DBA Dash Errors (24 hours). Could you please share any SQL Script to remove the duplicate key errors.

![image](https://github.com/user-attachments/assets/3488e498-43cb-4e72-b520-d0900c6a7739)

**Comment by DavidWiseman** [comment]
Hi, you might get these errors if you have two instances of the service running.  Have you installed it as a service but also have it running as a console application?  Or maybe setup two services monitoring the same instances?

**Comment by chaithanyagade** [comment]
Hi David,

Thanks for your email. I don't think I have two instances with same setup. How do we check that I installed twice or having two instances?

[cid:0ea57e5f-65de-4672-ad6e-34d16f85ff43]





Regards,
Chaithanya
Database Engineer
+91-9866369038
________________________________

**Comment by DavidWiseman** [comment]
First check on the machine where you installed DBA Dash service.  Open Task Manager and go to the Details tab.  Sort by Name and see how many copies of DBADashService.exe are running.  If you add the "Command Line column, you can see where they are running from.  If you have two and they are both running from the same location, someone might be running it as a console application - check the user name column.

DBA Dash logs information about the service used to import data.  You could try this query which will show the agents associated with active instances.  

```
SELECT * 
FROM dbo.DBADashAgent A
WHERE EXISTS(SELECT 1 
		FROM dbo.Instances I
		WHERE I.ImportAgentID = A.DBADashAgentID
		AND I.IsActive=1
		)
```

It's a last one wins so if there are two agents running it's possible only one of them might be visible when you run the above query and it might keep changing between them.  If you remove the WHERE clause from the above query it will give you the full list of possibilities.

```
SELECT * 
FROM dbo.DBADashAgent A
```

The other possibility I can think of is that the instance is listed twice in the source connections.  This might occur if you have slightly different connection strings that point to the same instance.

Hope this helps,

David

**Comment by chaithanyagade** [comment]
Thanks David. It seems like resolved after removing duplicate source connection from the monitoring list. I will confirm you after 48 hours.
Really, Thanks for your quick response.



Regards,
Chaithanya
Database Engineer
+91-9866369038
________________________________

**Comment by chaithanyagade** [comment]
Thanks for your help.





Regards,
Chaithanya
Database Engineer
+91-9866369038
________________________________
