### ISSUE TITLE
Instance offline

### ISSUE THREAD

**Issue by danw305** [trimble-oss/dba-dash#1160]
Hi

After removing the database connection and adding the instance again, DBA Dash GUI would not find the instance. 

In the config tool, the connection string was good and the service was restarted

It wasnt until updating the table "instances" and setting the "IsActive" to 1 that it appeared.

**Comment by DavidWiseman** [comment]
Hi,

When you removed the connection from the config tool you should have been prompted to mark the connection as deleted in the repository database (IsActive=0).

![image](https://github.com/user-attachments/assets/2c0268d6-3747-4223-83e0-c6d67f1362d9)

You can also make the selection in the "Grid delete action" combo box but it defaults to prompt.  This feature was added for #995 to make it easier to remove instances from DBA Dash.

If you do this by mistake, you can retore the instance in the GUI by going to the "Recycle Bin" folder.

Hope this helps,

David
