### ISSUE TITLE
Blocking Grid Not Showing Blocker SPID for Review

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#125]
When I go to one of the blocking snapshots under Running Queries and see a blocker on the SPIDs, sometimes I will see a blocker SPID that doesn't also show up on the grid as a running query.  If I select the "Show Root Blockers" it does not have the data to show.  I'm not sure if this is because we are using a contained user for connectivity to our Azure SQL DB instead of the sysadmin account at the server level or not.  It could be that this blocking SPID is actually from TempDB contention and that data can't be gathered because the user is contained.  Just wanted to pass along the issue in case you know anything about it.

**Comment by DavidWiseman** [comment]
The query to capture running queries is [here](https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLRunningQueries.sql)

It filters out system sessions.  For Azure, it will also filter for sessions in the current database.  It's possible that the session causing the blocking is been filtered out by this criteria.
