### ISSUE TITLE
Enable service to pull data from multiple connections concurrently

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#131]
When you have a large number of connections and you add a new connection in the config tool and then restart the service, it seems that it gets quite bogged down and behind on capturing data for connections that were already being monitored, therefore creating a large gap in the data.  Would it be possible to allow concurrent data pulls from the service to allow more to happen at once?  Maybe a configurable value in case people put it on a smaller server, but we are currently running it from a pretty beefy server that has plenty of resource overhead.

![image](https://user-images.githubusercontent.com/29784949/162508382-26517884-3784-4a71-9fab-d866a8ad4843.png)

**Comment by DavidWiseman** [comment]
One quick thing to check is the Logs folder or click "View Service Log".  See if there are any instances it's failing to connect to as this can slow things down with service stop/start.  
There is a setting to control the number of service threads used by Quartz - ServiceThreads in the ServiceConfig.json file.  
Another option could be to split the connections over two agents.  You can run two agents on the same box by setting a unique service name in the ServiceConfig.json file.
There might be other improvements I can make to the tool which I'll look at at some point.  Hope this helps.

**Comment by jacobgexigo** [comment]
Sounds good, thank you much.  I'll take a look

**Comment by DavidWiseman** [comment]
Closing issue.  Assuming this was resolved by configuration changes.  I am interested in making improvements in future to improve how the service scales.
