### ISSUE TITLE
Freeze Key Column in Grids

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#133]
Would it be possible to freeze the key column on each grid?  Sometimes the number of records will make it hard to visually track across a row when horizontal scrolling.  Here is an example:

![image](https://user-images.githubusercontent.com/29784949/162835918-b265df0a-ed66-4659-ac78-f5ed0ddeae4e.png)

**Comment by DavidWiseman** [comment]
Yes I think this should be possible. Probably an easy fix - I'll take a look.  Export to excel might be a workaround for now.

**Comment by DavidWiseman** [comment]
Fix will be included in the next release.

**Comment by DavidWiseman** [comment]
Fix is now in the latest release
