### ISSUE TITLE
No data on Slow Queries tab

### ISSUE THREAD

**Issue by dmartesi** [trimble-oss/dba-dash#135]
Hi, DBA Dash is collecting all kinds of data from my instance, but Slow Queries tab is always empty.
There's no filter applied.. it seems there's no data at all to show.

Any idea on what's going wrong?

**Comment by DavidWiseman** [comment]
The slow query capture isn't enabled by default.  Check the service configuration tool on the Source tab. In the grid of existing connections check the slow query threshold.  A value of -1 is disabled.  Set it to 1000 to capture queries with execution times longer than 1 second. 
When adding new connections there is a checkbox you can use to enable.  
If you already have slow query capture enabled you might not have queries that meet the threshold.  
You could run a command that takes longer than the threshold in ssms to check. e.g
`WAITFOR DELAY '00:00:02';`
There will be a delay of around 1min before this shows in dba dash after execution. 
Let me know if this helps.

**Comment by dmartesi** [comment]
Hi David,
thank you very much, problem solved!

**Comment by DavidWiseman** [comment]
Great 👍 Hope you find DBA Dash useful.
