### ISSUE TITLE
System.IO.IOException: The network path was not found.

### ISSUE THREAD

**Issue by Kilsgaard** [trimble-oss/dba-dash#205]
Hi

Can anyone help with this error?
System.IO.IOException: The network path was not found.
   at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKeyCore(RegistryHive hKey, String machineName, RegistryView view)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
   at DBADash.DBCollector.collectDriversWMI() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1341
![image](https://user-images.githubusercontent.com/11911747/170027683-10e5fcb6-910c-4d86-9cb1-ac71e9aae34a.png)

I get the error when trying to run dba-dash, against windows 10/11 conputers running SQL 2019 Developer.
The dba-dash service have administrator access to the computer and the sql server.
have tried with firewall enabled or disabled.
The error only persist on windows 10/11 computers on servers it works fine.

I would like to run with the WMI service, to collect all data avaliable.

/Graves

**Comment by DavidWiseman** [comment]
It's failing on this command:
````C#
var PVKey = RegistryKey.OpenRemoteBaseKey(RegistryHive.LocalMachine, computerName, RegistryView.Registry64).OpenSubKey("SOFTWARE\\Amazon\\PVDriver");
````
Line 1341 [here](https://github.com/trimble-oss/dba-dash/blob/main/DBADash/DBCollector.cs)

This is to get the PV driver version from the registry if you are on AWS.  If you are not on AWS, it should return null rather than fail.  I think for some reason it's unable to connect to the computer.  Or maybe the account doesn't have permissions.

Can you check if the computer name returned from this query is what you are expecting?
````SQL
SELECT SERVERPROPERTY('ComputerNamePhysicalNetBIOS')
````

**Comment by Kilsgaard** [comment]
Hi 

thanks for the info, I have now figured how to get it working (i think):

I have tested by using Linqpad7, with the code from line 1341:
To get it working i did the forllowing:
	Enable-PSRemoting -SkipNetworkProfileCheck -Force
		For powershell and Windows powershell

Set trusted host:
        On the computer:
  	Set-Item WSMan:\localhost\Client\TrustedHosts -Value 'servername' -Concatenate
        On the server:
	Set-Item WSMan:\localhost\Client\TrustedHosts -Value 'PC-navn' -Concatenate
	
Activate the service:
	Remote Registry

Firewall:
         It might be necessary to open some of the remote management ports on the windows firewall on the windows computer.
         I have not figured out what ports it is yet, on one of the computers I needed to enable remote management ports, 
         enabled to many, so have no clue what port it was (will get back if I figure it out)
         But on other computers there were no issues.

I will update if I find more info :-)

**Comment by DavidWiseman** [comment]
I came across an issue where the call was blocked on a server by the firewall.
```C#
var PVKey = RegistryKey.OpenRemoteBaseKey(RegistryHive.LocalMachine, computerName, RegistryView.Registry64).OpenSubKey("SOFTWARE\\Amazon\\PVDriver");
```
The solution was to enable the inbound firewall rule "File and Printer Sharing (SMB-In)" - TCP 445.

Also, you can enable these firewall rules to allow the WMI queries to work:
Windows Management Instrumentation (ASync-In)
Windows Management Instrumentation (DCOM-In)
Windows Management Instrumentation (WMI-In)

**Comment by DavidWiseman** [comment]
Updated docs [here](https://github.com/trimble-oss/dba-dash/blob/main/Docs/Security.md#Firewall)
