### ISSUE TITLE
Exclusion Filtering on Slow Queries Tab

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#219]
There is a way to filter the Slow Queries to see something specific, but would it be possible to also allow to filter out things you don't want to see?  Could even just be on the bottom details pane.  So if I know a specific user is running some queries and I want to exclude them from my view for now, I would add them to the exclusion filter and I would see all the rest of the queries.

**Comment by DavidWiseman** [comment]
Hi,  thank you for the suggestion. I might consider ways to add some exclusion filtering in future.  As a workaround you can query the repository database directly when more complex filtering is required.  The query below will give you a starting point:

```SQL
SELECT D.name AS DB,
       SQ.event_type,
       SQ.object_name,
       SQ.timestamp,
       SQ.duration,
       SQ.cpu_time,
       SQ.logical_reads,
       SQ.physical_reads,
       SQ.writes,
       SQ.username,
       SQ.text,
       SQ.client_hostname,
       SQ.client_app_name,
       SQ.result,
       SQ.session_id
FROM dbo.Instances I 
JOIN dbo.SlowQueries SQ ON I.InstanceID = SQ.InstanceID
JOIN dbo.Databases D ON SQ.InstanceID = D.InstanceID AND SQ.DatabaseID = D.DatabaseID
WHERE I.Instance = '{InstanceName}' -- Instance Name here
AND SQ.timestamp >='20220610 07:00' -- UTC
AND SQ.timestamp <'20220610 08:00' -- UTC
AND SQ.username <> 'User1234' --User to exclude
```

Hope this helps

**Comment by DavidWiseman** [comment]
Filtering improvements to be included in the next release.

**Comment by DavidWiseman** [comment]
Fix is available in the latest release.
