### ISSUE TITLE
Availability Group collection fails on SQL 2012 & SQL 2014

### ISSUE THREAD

**Issue by L3onard80** [trimble-oss/dba-dash#310]
Env: SQL Server 2014SP3 CU4 two replicas (AlwayOn Availability Groups).
Errors report:  `Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'seeding_mode'.`

Reading MS Doc: [Automatic seeding](https://learn.microsoft.com/it-it/sql/database-engine/availability-groups/windows/automatic-seeding-secondary-replicas?view=sql-server-ver16) this behavior is present from SQL 2016+

as reported by David on the Slack channel these are the two queries to fix.:
https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLAvailabilityGroups.sql
https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLAvailabilityReplicas.sql

**Comment by DavidWiseman** [comment]
Availability group collection bug is fixed in 2.22.3 🎉
