### ISSUE TITLE
Arithmetic overflow error converting float to data type numeric

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#312]
Hi David,

I got to know about the DBADash some days ago and after some testing and evaluations I got it installed on start collecting data. I have found some smaller issues in the application, among them this one shown in the image. This happens only on one of my SQL instances (SQL 2017 Standard Edition (64-bit) RTM CU29).

![math_overflow](https://user-images.githubusercontent.com/40255900/191668346-0765932d-0fb4-4f92-aab2-14460539d89e.png)

**Comment by DavidWiseman** [comment]
Thank you for reporting this issue.  I will investigate.

**Comment by EsQueEl-Fella** [comment]
Thanks for reply and investigation. The bug is not causing any problems. I will wait for the final solution and skip the workaround for now because later on I may forget to reactivate the feature :D.

**Comment by DavidWiseman** [comment]
This issue can occur if you create an identity column on a decimal or numeric data type.  It's a bit unusual to see these data types used for identity columns.  BIGINT supports 9,223,372,036,854,775,807 rows.
I might just exclude identity columns on data types larger than BIGINT as it's unlikely these will run out of values.

**Comment by DavidWiseman** [comment]
Fixed in 2.22.4 🎉
