### ISSUE TITLE
What server is being currently investigated? 

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#319]
I'm not sure if this could be filed as a feature request or (from end user perspective) an issue. I let this one for you to decide.

In many of tabs it isn't clear which server is currently on the focus. This is in many cases really confusing. Check the image attached. I got here by clicking on one my servers and some minutes later I wasn't sure which server this one was as I have many of them with the same databases. All I could say was, this is a one of my many empty (newly installed as a template) database servers. I could also make other screenshots but I think the attached image clearly demonstrate my point.

It should be possible to say, at all time, what Server we are currently investigating. 

![where_am_i](https://user-images.githubusercontent.com/40255900/191961952-bad554a9-3b60-4ed9-85b4-cf602a00337b.png)

**Comment by DavidWiseman** [comment]
Thanks for the suggestion - It should be possible to put the server name in the title bar.

**Comment by DavidWiseman** [comment]
The current position in the tree is highlighted when using the tree to navigate:
![image](https://user-images.githubusercontent.com/33157668/192085134-667e2c92-1f37-4d5f-be20-d08cae00de6d.png)
The position is just the current instance/db - it could be expanded to show the full tree path.

For the DB space tab you can navigate down from the root level Checks node to view a specific instance.  You are still at the root level of the tree but are viewing an individual instance.  The tab page should be changed to show the selected instance\db.

**Comment by EsQueEl-Fella** [comment]
I agree with your suggestion / explanation BUT that wasn't the main point of the opened issue. 

We need to have a foucs on User Experience here.

One way or another anyone could find where he/she currently is. This of course means additional user clicks and wondering around which in return results in end user time loss / focus. End users shouldn't wonder around in the application but use the features and focus on the data/tasks. 

Additional clicks also means extra queries which will be sent back to DB server and ... rest should be known to everyone.

And just for additional explanation how I ended up to the image I sent:
1- Click the "Checks" in the root folder
2- Click the "DB Space" Tab
3- Click on one of the Servers Link
4- Went for a short coffee Break :D 
5- Came back and I wasn't sure where I am

I would probably know where I was if I had a unique database on the server but as I mentioned before, the server in the image is just a template server and I got many of them at the same time so the identification over unique hosted DBs isn't possible.

I find the idea of adding the Server Name to the Main Window Title (or something similar) is a good one for a start and relatively easy implementation. 

Another (maybe a bit more complex) idea would be: After clicking any Server Link in the main panel (from the root level or ANY other location), the selected server should be synced in the navigation panel as selected item in the navigation tree. This idea is also covers very well from the logical point of view because if one is reviewing the data of ONE server, then he/she has left the overall review at the root level and also it is alway important to let the end use know where he/she is. Implementation of this ideas may of course require additional stuff to be taken into account.

**Comment by DavidWiseman** [comment]
Some usability improvements are coming in this area. It will now look like this at the root level when you drill down:
![image](https://user-images.githubusercontent.com/33157668/192096614-67487ad4-13ac-454b-b742-a8120a0cec3c.png)

Similar changes will be made elsewhere to ensure you always know what instance you are looking at.

**Comment by DavidWiseman** [comment]
The fix is included in 2.22.5 🎉
