### ISSUE TITLE
Modal Windows blocks access to the application

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#323]
Here one issue I just discovered.

The "RPC Completed / Batch Completed Event" which is acting as a modal Windows blocks the access to the rest of the application. From the end user perspective this is not practical. And as we are not expecting any input from the end user, this is also not OK from application point of view. 

![modal_window](https://user-images.githubusercontent.com/40255900/192084334-e86d72dd-cecd-49db-85a1-5d9aaf65a5b8.png)

**Comment by DavidWiseman** [comment]
This is easy to fix

**Comment by DavidWiseman** [comment]
To be included in the next release

**Comment by DavidWiseman** [comment]
The fix is included in 2.22.5 🎉
