### ISSUE TITLE
Last Good Check DB and Read Only Database Situation

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#325]
Here a bit more tricky case than previous ones I reported.

![last_good_checkdb](https://user-images.githubusercontent.com/40255900/192099524-73af7dc1-5988-40c2-8dc0-c4fca67959cf.png)

The image shows a set of databases that are being reported critical because the Last Known Check DB are way back the resonable time (Default DBDash Settings).

The report is TRUE but at the same time is also NOT quite TRUE.

It is TRUE Because:
I dog a bit in the DBDash code and found the origin of the reported values (hopefully the right place DBADash/SQL/SQLLastGoodCheckDB.sql). 

Assuming I am not lost in the code, the base data is relying on the date value reported by DBCC DBInfo 

	INSERT INTO @LastGoodDBCC(database_id,LastGoodCheckDbTime)
		SELECT TOP(1) @DBID, CAST(Value as DATETIME)
		FROM @dbinfo
		WHERE Field = 'dbi_dbccLastKnownGood'

Now these databases are in READ ONLY mode which in return means no changes to the database can take place ! Including the DBCC activities.

so It is NOT quite TRUE because:
DBCC Check is also taking place for READ ONLY DBs (at least in my case I make sure of that) but the result can't be recorded to the DB itself hence the report is taking the last known date value in the DB which ends up to a partially wrong report and conclusion.

What I couldn't understand is:
Actually we are filtering out the databases which are in READ_ONLY mode so why these DB are part of the resultset/report at all?

	DECLARE DBs CURSOR FAST_FORWARD READ_ONLY FOR
	SELECT name,database_id
	FROM sys.databases
	WHERE state  = 0
	AND DATABASEPROPERTYEX(name, 'Updateability') = 'READ_WRITE'

I admit one could go on discussing this case to an infinity level :D (Hen/Egg story style) but the main point here is: I see RED in the Application Root Page, I get Panic, I rush to check and I relaize, well False Alarm, these are my old dudes who were put to sleep long ago.

I also admit one can filter these and similar cases out but this means if the DBs go back to READ/WRITE mode, then one must know about this filter and remove them. Having 100s or maybe 1000s of DBs, this is not practical.

The solution to this issue may not be as easy as it seems and probably may involve some kind of compromis.

Here some ideas from my side: 
- Take the READONLY DBs for DBCC evaluations into accout but during the reporting make sure they are represented in a specific way
- Or leave them out in Generic Reporting 
- And optionally create a dedicated reporting for them

**Comment by DavidWiseman** [comment]
It will only loop through the databases to get the last good DBCC on older versions.  It will run this on newer versions (due to the earlier ` DATABASEPROPERTYEX(DB_NAME(),'LastGoodCheckDbTime')`  check:
```sql
	SELECT database_id,CAST(DATABASEPROPERTYEX(name,'LastGoodCheckDbTime') as DATETIME) as LastGoodCheckDbTime
	FROM sys.databases
```
It makes sense to filter out the readonly DBs for reporting purposes as there is no way to know the true time of the last DBCC.

**Comment by DavidWiseman** [comment]
Fix for this will be included in the next release.  It can be hot fixed using:

```sql
CREATE VIEW dbo.LastGoodCheckDB
AS
SELECT I.InstanceID,
	D.DatabaseID,
	I.Instance,
	I.InstanceDisplayName,
	D.name,
	D.state,
	D.state_desc,
	D.is_in_standby,
	D.LastGoodCheckDbTime,
	DATEADD(mi,CASE WHEN D.LastGoodCheckDbTime = '19000101' THEN 0 ELSE I.UTCOffset END,D.LastGoodCheckDbTime) AS LastGoodCheckDbTimeUTC,
	DATEDIFF(hh,NULLIF(D.LastGoodCheckDbTime,'19000101'),GETUTCDATE()) AS HrsSinceLastGoodCheckDB,
	DATEDIFF(d,NULLIF(D.LastGoodCheckDbTime,'19000101'),GETUTCDATE()) AS DaysSinceLastGoodCheckDB,
	S.Status,
	CASE S.Status WHEN 1 THEN 'Critical' WHEN 2 THEN 'Warning' WHEN 3 THEN 'N/A' WHEN 4 THEN 'OK' ELSE NULL END AS StatusDescription,
	CASE WHEN cfg.InstanceID IS NULL THEN 'None'
	WHEN cfg.DatabaseID = -1 AND cfg.InstanceID =-1 THEN 'Root' 
	WHEN cfg.DatabaseID = -1 THEN 'Instance'
	ELSE 'Database' END AS ConfiguredLevel,
	cfg.WarningThresholdHrs,
	cfg.CriticalThresholdHrs,
	excl.LastGoodCheckDBExcludedReason,
	D.create_date,
	DATEADD(mi,I.UTCOffset,D.create_date)  AS create_date_utc
FROM dbo.Databases D 
JOIN dbo.Instances I ON I.InstanceID = D.InstanceID
OUTER APPLY(SELECT TOP(1) T.*
			FROM dbo.LastGoodCheckDBThresholds T
			WHERE (D.InstanceID = T.InstanceID OR T.InstanceID = -1)
				AND (D.DatabaseID = T.DatabaseID  OR T.DatabaseID = -1)
				ORDER BY T.DatabaseID DESC, T.InstanceID DESC
			) cfg
OUTER APPLY(SELECT STUFF(CONCAT(CASE WHEN D.state<>0 THEN ', ' + state_desc ELSE NULL END,
					CASE WHEN D.is_in_standby=1 THEN ', STANDBY' WHEN D.is_read_only=1 THEN ', READ ONLY'  ELSE NULL END,
					CASE WHEN EXISTS(SELECT * FROM STRING_SPLIT(cfg.ExcludedDatabases,',') SS WHERE d.name LIKE RTRIM(LTRIM(SS.value))) THEN ', name' ELSE NULL END,
					CASE WHEN D.LastGoodCheckDbTime IS NULL THEN ', Not captured' ELSE NULL END,
					CASE WHEN DATEADD(mi,I.UTCOffset,D.create_date) > DATEADD(mi,-cfg.MinimumAge,GETUTCDATE())  THEN ', create_date' ELSE NULL END,
					CASE WHEN cfg.WarningThresholdHrs IS NULL AND cfg.CriticalThresholdHrs IS NULL THEN ', No threshold' ELSE NULL END
					),1,2,'') as LastGoodCheckDBExcludedReason
			) excl	
OUTER APPLY(SELECT	CASE WHEN excl.LastGoodCheckDBExcludedReason IS NOT NULL THEN 3
					WHEN DATEADD(mi,I.UTCOffset,D.LastGoodCheckDbTime) < DATEADD(hh,-cfg.CriticalThresholdHrs,GETUTCDATE()) THEN 1 
					WHEN DATEADD(mi,I.UTCOffset,D.LastGoodCheckDbTime) < DATEADD(hh,-cfg.WarningThresholdHrs,GETUTCDATE()) THEN 2
					ELSE 4 END AS Status
			) S
WHERE D.IsActive=1
AND I.IsActive=1
```

**Comment by EsQueEl-Fella** [comment]
Thx for the fix. Applied the fix and the report is now correct

![last_good_checkdb_fixed](https://user-images.githubusercontent.com/40255900/192120287-89e357fd-ce5e-4475-95aa-f76a481c084a.png)
