### ISSUE TITLE
One can open infinite number of Code Viewer Windows

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#335]
Probably would be better to let user reuse an already opend generic Code Viewer Window.

![too_many_code_windows](https://user-images.githubusercontent.com/40255900/192446623-d10238bc-7049-419d-bef8-b1be51749efd.png)

But, if we need many Code Viewer Windows, then we should at least identify each Window (for instance with Session ID) and tag and bound them to each Column. Something like the image below:

![code_windows_sessionid](https://user-images.githubusercontent.com/40255900/192448422-a94e7a43-11e9-476c-8895-8a2cba0a9212.png)

**Comment by DavidWiseman** [comment]
It should be possible to configure the code viewer to display a single instance while still allowing the parent form to be usable.  It's probably not going to be worth the effort of keeping track of multiple code windows and working out if a new one should be launched.  It could either work as a single instance (still allowing access to the main form) or allow unlimited instances to be launched.

**Comment by DavidWiseman** [comment]
Fix included in 2.22.6 🚀
