### ISSUE TITLE
Modal Code View Window in Slow Queries

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#336]
I am currently using version 2.22.5. 

As noted, the image shows a Code View Window which is acting as a Modal Window. 

![another_modal_window](https://user-images.githubusercontent.com/40255900/192453431-542aab35-24bc-4437-a636-1bafedb567a3.png)

**Comment by DavidWiseman** [comment]
Fix included in 2.22.6 🚀

**Comment by EsQueEl-Fella** [comment]
Thanks for the changes but the issue is partially solved. 
Now we got the Code View Windows defined as "On the Top" at all time. This causes other Problems for the user

![ontop_window](https://user-images.githubusercontent.com/40255900/192592921-e6f03006-8399-4519-8e38-b27183b7fd46.png)
