### ISSUE TITLE
Missing Chart / Diagram Name

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#337]
The Title / Name of the Chart is missing. 

One can guess what the Chart shows or hover the mouse and review the Tool Tip Text. It is still a guessing game thought as in the Tool Tip says: 'SQL Process' and 'Other'

![missing_diagram_name](https://user-images.githubusercontent.com/40255900/192457378-41e78a28-c2db-489c-ab57-ee1e566a23b8.png)

**Comment by DavidWiseman** [comment]
Removed in error by #277

**Comment by DavidWiseman** [comment]
Fix included in 2.22.6 🚀
