### ISSUE TITLE
Memory Clerk Tab is not updating table values

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#346]
**Important issue**. It is a bit difficult to notice that at the first glance:

If one selects a value in the memory tab for the first time, the pie chart will disapear and the line chart will load and shows the chart for the selected Memory Clerk Type. Now if one changes the server the line chart will change but the table values in the Memory Clerk Tab are NOT changed. This is a **bad Bug** as one may think and believe the values shown are belonging to the selected server (but they aren't) ! 

Oddly enough selecting one value again and switching the servers the line chart will show the correct values for the selected server but table values won't sync to the selected server values :D.

Review the image attached and you will discover the above oddity very fast. The line chart shows the MEM_BPOOL of a server with much more RAM (32G in Total) but the table values are from a server with 8G RAM in Total (and at this point I don't even know which server, not even by looking at the DBADash Titlebar, thanks to the recent changes ;D !)

**There is also a second issue**. Chosing an interval for the x-axis will be reset everytime the server node changes ! This isn't OK as one should not be forced to adapt the scale every time. If we are intending to comapre a situation, we need to have the same scale. Switching back to a mimimum default value will surely falls out of focus at one point and makes the comaprison of the server charts properly impossible or are invalid.

![memory_data_nosync](https://user-images.githubusercontent.com/40255900/192843367-91c338dc-67aa-411d-9a42-02f6c5911c44.png)

**Comment by DavidWiseman** [comment]
This issue is fixed in 2.22.8.  🎉

Thank you for including detailed instructions to reproduce the issue.
