### ISSUE TITLE
Different Modal Windows blocking the access to the main application.

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#352]
Hi,

I have discovered additional Modal Windows blocking the access to the main application. Version used: 2.22.8.
-Database Schema Diff Window
-Agent Job Diff Window
-Service Log Window (DBADash Service Config)

![db_diff_modal](https://user-images.githubusercontent.com/40255900/193297220-7b473bbc-8cd5-4fbf-a002-64d29384fc45.png)

![job_diff_modal](https://user-images.githubusercontent.com/40255900/193297267-8c807730-e072-468f-a33f-47064ed4feea.png)

![service_log_modal](https://user-images.githubusercontent.com/40255900/193297752-a41a1ba6-2064-4a3c-aeb4-27ea2560b759.png)

**Comment by EsQueEl-Fella** [comment]
Here you are I just found another Modal Window :D, Version used 2.22.8

![io_perf_modal_window](https://user-images.githubusercontent.com/40255900/193554556-d6234dac-363c-4daa-b0f9-d983e6ec5fc7.png)

**Comment by EsQueEl-Fella** [comment]
2 more Modal Windows. Used Version: 2.22.8

![manage_instances](https://user-images.githubusercontent.com/40255900/193871144-c43aef1a-f903-46f4-8faa-4a0d818006e9.png)

![data_retention](https://user-images.githubusercontent.com/40255900/193871188-b299cddc-187e-42a3-88d9-f244ef402136.png)

**Comment by DavidWiseman** [comment]
Included in 2.33.0 🎉
