### ISSUE TITLE
"Check for Updates" button and missing Internet connection

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#353]
Hi,

Version used: 2.22.8

The image shows some smaller issues:
- "Check For Updates" button (DBADash Service Config Application) opens up the "About" Window. This isn't an error but it is also not quite correct. A different lable for the button or a different / combined Title for the Window would save the day.
- If the server doesn't have internet access, pressing the "Upgrade" button will end up to an empty Warning Dialogbox. No message :D

I haven't tested what would happen if the Server had Internet access. 
- Do we only get an Update file? (Then it isn't an upgrade action. I assume "Download" would be a better choice as the lable)
- Or are we going to have an inplace Upgrade?

![upgrade_no_internet](https://user-images.githubusercontent.com/40255900/193299757-b45c1894-64ac-4071-8f05-fbd7b84213c8.png)

**Comment by DavidWiseman** [comment]
The upgrade process is fully automated if the server has internet access.  It runs [this script](https://github.com/trimble-oss/dba-dash/blob/main/Scripts/UpgradeDBADash.ps1).

I'm not sure if I'll change the labelling but there should be a better experience for servers without internet access.  The upgrade button could probably just be disabled if the version check isn't successful.
