### ISSUE TITLE
Incorrect values in DB Space History charts

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#354]
Hi

Version used: 2.22.8

The image shows the chart in "DB Space" tab for the tempdb database (as an example). The issue here is the chart values which are incorrect. At the x-axis with value 0 MB, one smaple point I marked, tempdb is 947 MB ! This value is so small compare to the scales on y-axis that is ploted as 0 MB. 

![incorrect_chart_values](https://user-images.githubusercontent.com/40255900/193303332-62795781-23eb-491d-b9ae-2d3a2dbe2af5.png)

**Comment by DavidWiseman** [comment]
The number format is a little confusing to me as it's been localized.  Normally we have commas for thousands separator and period for the decimal point.  

It looks like the top of the chart is ~200GB and the point close to zero is 947MB.  That's under half a % of the charts max value so I think the chart is correct.  This is a quick mockup in Excel (Point 3):

![image](https://user-images.githubusercontent.com/33157668/193406984-ea61deb1-4b8f-4f5a-882d-efba26e8303e.png)

You can use this query to get the raw data:

```sql
exec dbo.DBFileSnapshot_Get @FromDate='2022-07-03 00:00:00',@ToDate='2022-10-02 00:00:00',@InstanceGroupName=N'your instance',@DBName=N'your db',@FileName=N'your file'
```

The sizes shown are the max sizes for each day.  It looks like the current size might be 210MB for tempdb - which seems a little odd if the max size is ~200GB in the chart.  This might occur if the instance was restarted and tempdb got re-created or if you shrunk the files.

Let me know if this explains the issue or if something is still off that needs investigation.

**Comment by EsQueEl-Fella** [comment]
The number format is in German (localized) and oddly enough (for non-german languages) the role of the "Point" and "Comma" in number notations are switched.

The focus of opened issue was to demonstrate the Chart behavior which isn't correct (to my opinion) and not the reported values. Simply said, values are correct but the chart isn't showing them correctly. On the Cord-System, x-axis at level 0 shouldn't present values **above** 0. The image I sent tries to demonstrate that.

To solve this (visually incorrect presentation) problem, we need to change/adapt the y-axis scales in a way that values above 0 don't land on 0-Line. **Maybe the issue can be solved if you would use Logaritmic Scales**.

The image below shows in detail what I mean. This time I am also adding some additional info:
- Tempdb on the server is made of 10 files each 20 GB fixed with no Authogrowth
- Tempfb Log file is also 10 GB and fixed with no Authogrowth
- This time I also removed the "Smooth Lines" in the Chart

![chart_values2](https://user-images.githubusercontent.com/40255900/193543846-618de783-898e-4693-a36f-16ce65f4cfeb.png)

**Comment by DavidWiseman** [comment]
On this scale, 947MB is exactly where it's supposed to be - it's 0.46% of the allocated pace.  947MB is almost nothing in comparison to the 200GB space allocated.  If you put the data into Excel you will see the same result.

![image](https://user-images.githubusercontent.com/33157668/193555056-dbb65427-3ec6-4cff-a562-2ae27b4bd663.png)

A logarithmic scale would definitely be more confusing.  I might consider an option to show the raw data in table format - this would make it easier to export to Excel and use some different charting options.

**Comment by DavidWiseman** [comment]
Next version will have an export to excel button - allowing you to create different charts easily. This is one of my lab tempdb databases with similar near zero values.  The normal chart lines up with what DBA Dash is showing.  The logaritmic one to me is misleading - but excel provides that option if you want to use it.

![image](https://user-images.githubusercontent.com/33157668/194146472-31590820-59c5-407f-bd8e-2837031a7f25.png)
