### ISSUE TITLE
Another case which allows one to open infinit number of Windows

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#355]
Hi

Verison used: 2.22.8

As the image shows, user can open infinit number of windows buy clikcing the "History" link 
-in the "DB Space" Tab (First image).
-in the "Drives" Tab (Second image). 
-in the "Files" Tab (Third image).

fig.1
![infinit_num_windows](https://user-images.githubusercontent.com/40255900/193306894-d323b07f-9046-43f1-abef-6b79bc1813ee.png)

fig. 2
![infinit_num_windows_2](https://user-images.githubusercontent.com/40255900/193308376-a2bc8ee4-905a-49b9-840b-cae367953351.png)

fig. 3
![infinit_num_windows_3](https://user-images.githubusercontent.com/40255900/193309426-366add7e-5677-4037-ab88-ea2b6092a1e4.png)

**Comment by DavidWiseman** [comment]
This should be able to work similar to the code viewer.  I'll take a look at some point.

**Comment by DavidWiseman** [comment]
Included in 2.33.0 🎉
