### ISSUE TITLE
Performance Summary riddles and puzzels

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#360]
Hi

Today I was reviewing the "PerfMon Summary" information (Version used 2.22.8) and I was wondering about following points below. It is worth to mention, all the data presented in all the issues are real world data and they are collected from productive systems refelecting real scenarios.

Starting from top to bottom (in the image):
- We got a column called "MB/Sec". I couldn't **clearly** decipher what this values is. Maybe a better column header would help. There are also no Tool Tips which explain the columns. This even could be implemnted as an additional feature: Tool Tip which explains the column headers in all the table grids, application wide.
- Column "Read Latency" shows a painted cell as warning. I was seraching on the server itself for a quite while and I couldn't find anything which would help me to identify and localize the issue reported **on the spot**. I then searched even more and eventually I discovered a way to get some values and responsibles for the latency. This was hard and to some extent cryptical but maybe there are better ways. Anyhow, this was my approach:

1. Switch to single server.
2. Click on "Performance" Tab
3. On the "IO Perfromance" chart click "View Table Summary" (Which is yet another Modal Window I discovered :D) and then review the reported values which by the way they aren't painted at this stage so if one isn't paying attention he/she will then miss the point and leave. 

The above just tried to demonstrate how cumbersome is to identify the reported problem in detail. I hope you would come up with a easier / better way to solve this case.

- Columns "Read Latecy" and "Write Latecy" are being painted as green. I really tried to understand **why**. I couldn't come up with any logic.
- There are some cells in "Critical Wait" column which are gray colored. **Why**? Value 0.00 can't be gray AND green at the same time!
- In "Lock Wait" and "Total Wait" columns, I find values way high in compare to the other similar values but these cells aren't painted at all. **Why**? Aren't we using any color indicators in theses columns? Shouldn't we do that?
- There are some cells in the "Read Latecy" with no values at all. **Why?** Isn't there any values existing or are they so small that could be ignored? If so, then why can't we show 0,0?

I am sure each one of the above questions can be answered one way or another but the MAIN point here is: 

The end user needs to **work** with these data and try not to decipher them. One way or another everyone (with enough 
persistence) can get along but that is also not the point of having the values collected. Application should do the most job for the user (because it is the tool, it is hard to keep track of these values and using visual effect one can transfer messages which helps the process.) and the user mostly needs to focus on identifying, anlasying of the collected data. This of course implies, collected data need to be precise and relyable on one hand and the application should try to avoid ambiguity on the other hand.

![perfmon_summary](https://user-images.githubusercontent.com/40255900/193550637-c2db8c0e-7635-4a58-b7fe-c50f70fe7e43.png)

**Comment by DavidWiseman** [comment]
There are explanations for these.  I will reply back and also look to improve documentation.

**Comment by DavidWiseman** [comment]
![image](https://user-images.githubusercontent.com/33157668/194018415-30db3491-ff21-492c-b20f-815fdf617c48.png)

**Comment by DavidWiseman** [comment]
I've added some [documentation](https://dbadash.com/docs/help/performance-summary/) for this now.
