### ISSUE TITLE
"Slow Queries" detailed table color coding and a different column sort order

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#363]
Hi,

this is a feature Request. Version Used: 2.22.8.

could you please  
- add a color coding to the column "Result" in "Slow Queries" detailed table (fig. 1). It helps for instance to identify (bad) things much much faster.
- provide the column sort order (in fig. 2) in the detailed table as "Default" application settings. I am aware one can move the columns manually but after an application restart things are back to app default. This saves up lots of time playing around with the scrollbars while one is trying to analyse the data.

fig. 1
![slow_queries_detail_1](https://user-images.githubusercontent.com/40255900/193789810-d695e986-bb0b-4df3-b210-6789227f4734.png)

fig.2 
![slow_queries_detail_2](https://user-images.githubusercontent.com/40255900/193789854-a2246aa2-7ec2-4c33-a557-d1891e0c6dc6.png)

**Comment by DavidWiseman** [comment]
If you are interested in failed query executions, the best option is to change the "Group By" to result.  You can drill down from there - or you could add a filter on the result column.  
I'll consider adding the highlighting though.  For sort order - I prefer to see the slowest queries listed first in most cases.

**Comment by EsQueEl-Fella** [comment]
Hi,

Thanks for Reply and I am happy to get the color coding at one point implemented.

With the "Sort Order" I only mean how the columns in the table are horizontally (and visually) ordered and NOT the data in each column. Instead of "Instance, Database, Event Type, Object Name, Time, ..., Result, Session ID, Text" in the table I suggest to have "Instance, Database, Result, Session ID, Text, ..." because the first important fact is to know what was slow (Text Column), who was slow (Session ID) and the success outcome (Result, specially as color coded). 

This will help to see the results at the first glance and there is no need to scroll to right in the table. This request might seem a bit unusuall for the developer but in real life scenarios similar improvments will save valuable time for the user. There are some other similar cases in the GUI application which I will let you know about.

**Comment by DavidWiseman** [comment]
The performance summary has an option to save the column layout so I might look to do something similar at some point.

**Comment by DavidWiseman** [comment]
2.23.1 Adds color coding for the Result column.
Also, a "Failed" has been added to the Summary grid.  This provides an easy way to see if any queries failed without changing the Group By to Result.  You can use the "Failed" column to drill down.

**Comment by EsQueEl-Fella** [comment]
Thx for the changes. I specially like the aaditional implementation of the new "Failed" column in the summary. Really helpful.

**Comment by DavidWiseman** [comment]
Saving the column layout will be in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 2.27.0 🚀
