### ISSUE TITLE
Some possible (minor) improvements for "DB Space" checks

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#370]
Hi,

As the image shows I got some minor issues as potential improvement candidates. Used Version 2.22.8

in the "DB Space" Tab I found
- Almost everywhere I checked MB scale seems to be a default in the DBADash application. Check the reported data in "Files" Tab or "Configuration / TempDB" Tab for instance. The GB scale used in "DB Space" Tab causes some round ups and results in some inaccurate visual reporting. The shown sample here is the "master" DB. Don't you think changing GB to MB scale would be a more proper approach?
- Databases in Readonly mode don't report any value in "Used GB" column. Showing no value doesn't seem to be OK. Why not showing 0,0?
- Empty cells in the table grid will show a wrong Tool Tip (also reported this one recently in another issue)

![db_space](https://user-images.githubusercontent.com/40255900/194177067-fc0220cd-f5ad-4dcb-abf1-cfba82a02a94.png)

**Comment by DavidWiseman** [comment]
Included in 2.24.0 🚀
