### ISSUE TITLE
"Failed" Folder

### ISSUE THREAD

**Issue by SQL-Snowball99** [trimble-oss/dba-dash#375]
Hi,

There is a folder consuming disk space  called "Failed" created inside the DBA Dash directory containing XML files. The contents of the files looks more like collection errors. Can you please explain what is the purpose of this folder, impact of deleting the contents thereof, and ways to limit the disk usage? 
![image](https://user-images.githubusercontent.com/104442916/194905658-daa09849-68e1-4d8d-ba37-be7cc7f7639b.png)

Thank you.

**Comment by DavidWiseman** [comment]
If there are any errors in writing the collected data to the DBA Dash repository db, the collected data will be written to the Failed folder to allow debugging.  The folder will clean up automatically after 7 days.  There is no harm in cleaning out this folder more regularly if needed.  

It might be worth looking to see what errors are in the DBA Dash error log.   There is a DBA  Dash Errors tab in the "Checks" node in the GUI.  Also, you might need to check the "Logs" folder (Also available in the service config tool) if you don't see errors there. If the errors look like a bug in DBA Dash - please report back with the error and I can investigate.  

If you want to see what is in the files, I [created a tool for this](https://github.com/DavidWiseman/SerializedDataSetViewer).  It's all the data that was collected for the failed collection.

Hope this helps,

David

**Comment by SQL-Snowball99** [comment]
Thank you David. It does make sense because most of the time when the folder fills the disk is because the Data/log file is full. Better management of the DBADash database storage is required from my side.

**Comment by DavidWiseman** [comment]
To keep the log file size in check you need regular transaction log backups - or switch to the SIMPLE recovery model.  If you want to manage the repository database size, it's possible to [customize the retention policy](https://dbadash.com/docs/help/data-retention/).  Hope this helps.
I'll close this issue.  If you need help with any of the errors just submit a new issue with the error details.
