### ISSUE TITLE
Short by byte field (like enabled) for the "Agent Job" tab

### ISSUE THREAD

**Issue by acappelletti** [trimble-oss/dba-dash#382]
Hi,
I want to report not a problem but an improvement in the sorting system of the columns.
For example I got many jobs and not seems to me possible short by "Enabled" like for the other text fields.

![image](https://user-images.githubusercontent.com/43847440/195609168-98b64f7f-96ed-462b-8bbc-0bb4e41bc1f0.png)

Alen

**Comment by DavidWiseman** [comment]
Sorting will be enabled in the next release 👍

**Comment by DavidWiseman** [comment]
Included in 2.24.0 🚀
