### ISSUE TITLE
Option for back/history button?

### ISSUE THREAD

**Issue by tvanzeleDelen** [trimble-oss/dba-dash#409]
Would it be possible to add a back button, so that you can go back to the previous screen(s)?

**Comment by tvanzeleDelen** [comment]
Maybe a home button would already work. Currently, when I'm on the home or start screen and I click on something for details, it unfolds the tree to that server, but because I have a lot of servers added, when I want to go back to the home, I have to close the tree for the server, scroll back up and select DBA Dash again. I agree that it's not really a problem, but it just would be handy.

**Comment by DavidWiseman** [comment]
Thanks for the feedback.  I hadn't considered the need to scroll with a larger number of servers.  I've only got ~40 but some other parts of Trimble have quite large numbers of instances.

**Comment by DavidWiseman** [comment]
I decided to take a look at this and it will be included in the next release.

![image](https://user-images.githubusercontent.com/33157668/201044870-f788ab3e-7a36-4fe0-824c-6bbd72f8b5a6.png)

Clicking the back button will take you to the previous node/tab.  Or if the control has a move back feature that will be triggered instead.  Mouse back button can also be used.
The home button takes you to the "Summary" page of the root node.

**Comment by DavidWiseman** [comment]
[Fixed in 2.26.0](https://dbadash.com/blog/whats-new-in-2.26.0/) 🚀
