### ISSUE TITLE
Backup info is missing

### ISSUE THREAD

**Issue by luizpcs** [trimble-oss/dba-dash#412]
Hi David,

I am using DBADash with several instances and realized that in some of them the backup information is not being captured, I checked and noticed that the instances which are with this problem, are instances that have the server_name in SQL Server different from the Host Name on the server, so I checked the SQLBackups.sql and found that the condition below is the cause of the information being missing.

WHERE server_name=@@SERVERNAME COLLATE SQL_Latin1_General_CP1_CI_AS

I know that changing the server_name in SQL Server solves the problem, but this happens in several instances and to change the server_name requires restarting the service, which is a very bureaucratic action to perform. Could you make some changes at this point or help me solve this issue?

**Comment by DavidWiseman** [comment]
Hi,

I'll investigate.  😊

Do you know how the situation came about?  Was the server renamed after installing SQL or was sp_dropserver/sp_addserver run to change the server name?  Was it done intentionally for some reason?  I don't think I need this info if you don't have it - I'm just curious.

Thanks,

David

**Comment by luizpcs** [comment]
It was renamed after installing SQL. The server was renamed because it did not comply with the company's naming rule.

**Comment by luizpcs** [comment]
Thanks, David
The DBADash is an incredible tool, great job!!

**Comment by DavidWiseman** [comment]
Fixed in 2.24.2 🎉
