### ISSUE TITLE
Database Source Not Alphabetical

### ISSUE THREAD

**Issue by tonyrumans** [trimble-oss/dba-dash#416]
When choosing a Source db would be nice if the dropdown was alphabetized

![image](https://user-images.githubusercontent.com/4450772/198125297-4a7978c1-bb4b-434d-95a3-b7b6499d2df7.png)

**Comment by DavidWiseman** [comment]
Thank you for the suggestion.  I'll get this fixed soon.

**Comment by DavidWiseman** [comment]
Fix to be included in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 2.24.2 🎉
