### ISSUE TITLE
Model db log backups flagged because not completed

### ISSUE THREAD

**Issue by turagittech** [trimble-oss/dba-dash#417]
The model database shows as not having had a log backup as it's in full recovery which is likely typical and Microsoft recommendation is to only do full backups. 

Maybe ignore log backups on model regardless of recovery mode

**Comment by DavidWiseman** [comment]
Hi, it's possible to exclude the model database from the backup checks.  On the backups tab, click the gears icon in the toolbar and select "Configure Root Thresholds".  Type "model" in the excluded DBs textbox.  This will exclude the model database from all backup checks at the root level
It's also possible to click the configure link for individual databases - remove the inherit checkbox and set some custom thresholds that exclude log backups.  The easiest option is just to exclude it at the root level though.
I normally like to change the model database to SIMPLE recovery model.  Any new DBs created would inherit this default recovery model.

Hope this helps.

**Comment by turagittech** [comment]
Ok, thanks for that. I'll look into possible changing to simple for the database, but excluded for now
