### ISSUE TITLE
Inconsistent Grid Sorting feature in Slow Queries

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#434]
Hi,

Used Version: 2.24.1

While using the Slow Queries grid I realized that its sorting facility is Inconsistent. The image shows the columns one can sort. 

![sortingrid](https://user-images.githubusercontent.com/40255900/201029909-75292131-fcd2-4772-ae48-9617f066a82d.png)

**Comment by DavidWiseman** [comment]
Thanks for reporting.  I'll fix it for the next release.

**Comment by DavidWiseman** [comment]
[Fixed in 2.26.0](https://dbadash.com/blog/whats-new-in-2.26.0/) 🚀
