### ISSUE TITLE
Adding a new Tab IO stats

### ISSUE THREAD

**Issue by Nele90** [trimble-oss/dba-dash#486]
Hey David,

Is it possible to add new IO performance tab to server performance section to have more info like write and read latency per data file?
Also, on performance view when disk latency is >200ms I can't see it, please see below.

![image](https://user-images.githubusercontent.com/65944528/208400379-d1e25f09-cb60-4087-9d3e-80d305f89de8.png)

**Comment by DavidWiseman** [comment]
Hi,

Thanks for the suggestion.  An IO performance tab might be useful.  The app doesn't give you a way to see charts per drive/db/file over time.  You can get per drive over time (select the drive filter) but you can't see all the drives together.  Also, if you click this button you can get a summary view for the selected time period.

![image](https://user-images.githubusercontent.com/33157668/208414667-0374078b-b97b-436a-a77a-1b98a9b15d3f.png)

You can see the IO grouped by Database, file group, file or drive which might help narrow things down.  You could also narrow the date range down to the period where you have high disk latencies - select Custom from the date filter at the top right of the app.

I think I set the scale of the chart to 200ms deliberately.  Ideally disk latency should be single digit milliseconds.  Above 20ms is poor.  If the scale was adjusted for the max value it would flatten out some of the other peaks.  Also you wouldn't be able to tell visually if the latency is poor by the position on the chart.  e.g. A Value near the top of the chart isn't a problem if the scale of the chart is up to 10ms.

Note: I would also look at your wait stats.  If you see PAGEIOLATCH or WRITELOG waits as your top wait types this provides some additional evidence of an IO bottleneck.  You might see high disk latencies if you have cloud storage and have exceeded your limits.  Snapshot style backups are also known to cause high disk latency as they freeze IO for a short period of time.  High disk latencies might not be a huge problem if the volume of IO is small and you don't see IO related waits as your top wait types.  You might also see higher disk latencies if you have maintenance operations running like DBCC checks - which might not be an issue if this is out of hours and they complete within your maintenance window.

Thanks,

David

**Comment by Nele90** [comment]
Thanks for your answer. 
Ah now it make sense with summary view, this is what i need just to have more info. 
Yes i realized that this latency was relate do C: drive. :-) 
I played around with Grafana dashboard i created some view, but the problem with it is that I can't exec sp directly from Grafana instead I have to exec your procs and insert into some table and then take this data and feed dashboard, in theory I could make similar look as your app, however i'm not sure if it make sense as your app provide all info without changing anything. :-D

**Comment by SasaJ7** [comment]
Understandable.

May I recommend one adjustment or change for line graphs?
How about to evaluate only the X cursor position within ling graph and provide relevant values popup instead of asking users to target lines to get that popup?

This would improve usability a lot.

Thanks

**Comment by DavidWiseman** [comment]
The tooltip behaviour is down to the charting control I use ([Live-Charts](https://v0.lvcharts.com/)) - I'm not sure if there is a way to fix it. I don't find it to be an issue to select the chart point to get the tooltip. It guess it might be harder depending on your display settings and input device (mouse is easier than a touchpad).  
This issue isn't likely to get looked at by me, but there is an option for someone else to fix it and submit a pull request.
Note: At some point I might [change to use version 2](https://github.com/trimble-oss/dba-dash/issues/35) of the control.  I might also look at other charting components, but Live-Charts is very good as a free and open source charting component.

**Comment by DavidWiseman** [comment]
[Improved in 2.43.0](https://dbadash.com/blog/whats-new-in-2.43.0/) 🚀

**Comment by Nele90** [comment]
Thanks David for adding this. :-)
