### ISSUE TITLE
Identity Columns Threshold configuration Adjusment

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#583]
Hi David,

I am currently Version: 2.38
Could you kindly provide a method to adapt this configuration using the Service Config Tool? This will take probalby 10 max 15 minutes one timer of your time but saves a lot of time for the end users in the future. It is also much safer to do such adaptions using the provided proper GUI than directly in the Backend DB.

![grafik](https://user-images.githubusercontent.com/40255900/228753396-ef8ac1a1-5415-4cbe-9fd3-186fb74ce5e7.png)

I suppose Fiddling around deep inside the repository database is not the main purpose of the DBADash. And most importantly It took me almost 30 minutes searching around every where to find out how to change the values and eventually I came accross the statement in the help. 

![grafik](https://user-images.githubusercontent.com/40255900/228754557-82837cab-533b-4891-911a-a0c090c2d4e0.png)

**Comment by DavidWiseman** [comment]
Included in 2.39.0 🚀
