### ISSUE TITLE
New database does not recognized by Agnet

### ISSUE THREAD

**Issue by ahozdemir** [trimble-oss/dba-dash#624]
Hi;

When I create New database, GUI does not show newly added database until restart the agent service,

regards

**Comment by DavidWiseman** [comment]
It runs the databases collection every 1hr by default or when the service is started.   Restarting the service is an option if you want to trigger the collection to run immediately or you can wait until the next scheduled run time.  If hourly collections are not frequent enough you can [change the schedule](https://dbadash.com/docs/help/schedule/).
