### ISSUE TITLE
Compress Expected Large Tables

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#642]
I wonder if you can add a flag to the GUI to allow for using SQL native DATA_COMPRESSION = PAGE for qualified SQL versions?  If it checks the repository database server and is developer or enterprise, allow the check box, otherwise grey out with a tooltip.  For tables like SlowQueries, keeping the default retention can mean a very large table if it is a very busy enterprise being monitored.  We have around eight repos for different things (separation of logic regions, etc.) and by enabling data compression on the SlowQueries table on all of them we saved 40% on the disk space.  Obviously we had to add it to the Switch.SlowQueries as well to allow the purging to happen for the retention.

**Comment by DavidWiseman** [comment]
Data compression is already used in a few places but it's possible I missed some cases where it might be beneficial.  We don't need to worry about versions/editions. The repository db requires SQL 2016 SP1 or later so we have compression on all editions.
Changing it for existing tables could be quite a time-consuming operation depending on the size of the tables.  The partition switching also adds some additional complexity as you noted.  If I implement the changes for #640 it should make it much easier for people to change the compression settings - The Switch tables would be removed.

**Comment by jacobgexigo** [comment]
Okay cool...yeah that will help and then it's just up to you to go compress yourself.  Sounds good.
