### ISSUE TITLE
Patching / SQL Server version compliance check

### ISSUE THREAD

**Issue by dv2287** [trimble-oss/dba-dash#656]
It would be useful if "Configuration\SQL Patching" section could be extended to perform and display compliance check of current instance build with the latest available SQL Server build (or custom selected build, ie. X cumulative updates behind latest version).

Example of such functionality in dbatools PowerShell module: https://docs.dbatools.io/Test-DbaBuild

Build references: 
https://dataplat.github.io/builds
https://github.com/dataplat/dbatools/blob/development/bin/dbatools-buildref-index.json
https://docs.dbatools.io/Update-DbaBuildReference

**Comment by DavidWiseman** [comment]
Thanks for the suggestion - I agree.  It's something I've considered adding.  There isn't an official source for this info though I saw some talk of creating one on Twitter a while back.  There are a few unofficial options - dbatools is probably one of the best options available given its popularity and the format is easy to consume.  

It might be useful to update this info on demand in the GUI and optionally schedule updates in the agent.

**Comment by DavidWiseman** [comment]
Included in 2.44.0 🎉
