### ISSUE TITLE
Top Contributors to Elastic Pool Usage

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#659]
I wonder if there might be a good way to show metrics on Elastic Pool usage as an intermediary layer between the total server and the individual database.  In cases where you have a single EP, it makes sense that performance, slow queries, running queries, etc. would be at the total server level.  But we have servers with 4 or 5 elastic pools and we just use the Server as the connection string consolidation layer.  In this case it would be nice to be able to group all of the metrics to the EP level too, so that we can see which database or set of queries is the one causing the most pressure in the EP.

**Comment by DavidWiseman** [comment]
I would use the Azure Summary tab and sort the databases by elastic pool.  This tab will allow you to identify which databases are contributing most to the resource consumption within the pool.  I would then focus on those databases.

**Comment by DavidWiseman** [comment]
The next version will include nodes in the tree for each elastic pool.

**Comment by DavidWiseman** [comment]
This is included in the 3.3. 🚀
