### ISSUE TITLE
Feature Request - Auto Refresh

### ISSUE THREAD

**Issue by csdunaway** [trimble-oss/dba-dash#668]
I love using the DBA Dash app. I love using the Performance tab most of the day. A new feature request I have is:

Have a way to auto-refresh the screen every minute or so.

**Comment by DavidWiseman** [comment]
Thank you for the suggestion.  The app originally had an auto-refresh but it was removed a while back - before the first public release I think.  I think the main issue was that it was trying to be smart about the refresh and load new data points incrementally.  This added complexity and it was also a little buggy.  The other downside to an auto-refresh feature is that it has the potential to add some additional load.
I might consider adding this feature again.  I don't think it would be too complicated to add more of a dumb auto-refresh feature that basically just runs the full refresh on a timer.

**Comment by csdunaway** [comment]
Thank you so much! I do love this app!

Thanks,
Clifton Dunaway
________________________________

**Comment by DavidWiseman** [comment]
To be included in the next release. 🚀

**Comment by DavidWiseman** [comment]
Included in 2.45.0 🚀
