### ISSUE TITLE
Acknowledging failed Jobs resets sorting and custom size of columns

### ISSUE THREAD

**Issue by HansLindgren** [trimble-oss/dba-dash#696]
When clicking **acknowledge** on a Job in the state 'Critical or Warning' it resets the sorting and custom size of all column.
Example:
* I click 'Acknowledge' in this screen:
![image](https://github.com/trimble-oss/dba-dash/assets/6190303/92017a51-27f7-4071-9541-1642a371ae73)
and it acknowledges this row but the sorting (that was on the column 'Job Name') and the custom size (on the same column) disappears and it now looks like this:
![image](https://github.com/trimble-oss/dba-dash/assets/6190303/4db115a4-2482-4f7e-b06b-d45e80ae147b)

**Comment by DavidWiseman** [comment]
Hi.  I think it will do a refresh after clicking the Acknowledge button which probably auto-resizes the columns and doesn't persist the previous client side sorting.  It would be better if it persisted the column layout and order as you suggested.

**Comment by DavidWiseman** [comment]
This will be fixed in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 2.47.0 🚀
