### ISSUE TITLE
Invalid Database

### ISSUE THREAD

**Issue by Vaelek** [trimble-oss/dba-dash#698]
While trying to run the config tool, the connection dialog connects to the db without issue, but once selected it always just says "invalid database" when I hover the X that appears on the plug button. The destination server is SQLServer 2016 SP3.

**Comment by DavidWiseman** [comment]
Hi, the destination database needs to be either:

* An empty database
*If any objects are detected the schema won't deploy.  This validation is to prevent you from overwriting the schema of another database by mistake.  If you created a new DB, maybe it already has objects in it.  Check the model database.*
* An existing DBA Dash repository database with the schema deployed previously.
*If you have deployed previously it's possible it failed for some reason and this prevents the validation check.  It might be worth deleting it and re-creating it*
* Doesn't exist
*The database will either be created when the service starts or when you click Deploy/Update Database.*

I would suggest removing the database and allowing the tool to create the database.

Hope this helps - let me know if you need some more assistance.

For reference, this is the validation check that is used:

```
IF EXISTS(
	SELECT * FROM sys.extended_properties
	WHERE major_id=OBJECT_ID('DBVersionHistory')
	AND name = 'AppID'
	AND value='74F9FD8A-DF22-4355-9A7A-6E1F4AE712B9'
)
BEGIN 
	SELECT TOP(1) Version
	FROM dbo.DBVersionHistory
	ORDER BY DeployDate DESC
END
ELSE IF NOT EXISTS(SELECT * 
			FROM sys.objects
			WHERE type NOT IN('S','IT','SQ')          
            )
        AND DB_ID()>4
BEGIN
	SELECT '0.0.0.0' AS Version
END
ELSE
BEGIN 
	RAISERROR('Invalid database',11,1)
END
```

**Comment by Vaelek** [comment]
Ok got it thank you. It was not clear that the database had to be empty. Perhaps that would be helpful in the quick start guide to mention.

**Comment by DavidWiseman** [comment]
Thanks for the feedback - I'll look to improve the documentation.  Hope you find DBA Dash useful.

**Comment by DavidWiseman** [comment]
Documentation has been updated 
![image](https://github.com/trimble-oss/dba-dash/assets/33157668/fbc20ce7-27b2-4e4c-a705-91e5210f3e59)
