### ISSUE TITLE
Tracking Running Queries by SPID, database, application, login, etc

### ISSUE THREAD

**Issue by clhambrick** [trimble-oss/dba-dash#747]
Let me start by saying I love this free tool.  It has helped me with tracking systems in my place of business tremendously as the company does not have the capacity to invest in a commercial monitoring tool.  I was trying to investigate one of the SPIDs within one of my systems and I found no real way to look at the running query data through a SPID filter.  This may not fit within what data you are trying to capture.  I also tried to look to see if there were any similar issues that users may have logged and did not see anytning that clearly tied into what I am trying to do .  If I am repeating something you may have already answered with another user, please disregard this issue.

Many times I have tracked SP_WHOISACTIVE data snapshots like every couple of minutes.  Not the best solution but just gives me the ability to see those queries that are long running and many times I can track them this way by the SPID.  I realize that there is query store and this maybe what I need to turn on as I will say I have not really started to use this yet but I was curious if there is any ability currently within DBADash to look at a SPID over the time you capture.  It shows at each iteration of the running queries and so maybe I simply need to figure out within the database how to query this myself, but I was just curious if at some point in the future do you think you might add in the ability to query the running queries data by various columns, like looking by database, or by applicaton, or by login or by SPID?

Thank you in advance for your response.

**Comment by DavidWiseman** [comment]
Hi, you could look at querying the dbo.RunningQueriesInfo view (note: times in the DB are stored in UTC).  You can also use RunningQueriesForSession_Get to get the running queries associated with a specific SPID.  This is what the app uses to link the slow queries with running queries data - which might be a way to do what you want to do in the app.

Assuming you have slow query capture enabled:
* Go to Slow Queries tab.
* Set a filter for the session ID you are interested in.
* This gives you the RPC/batch completed events of all queries associated with this session that took longer than 1 second to run (with the default threshold)
* Click the numbers to drill down and see the individual queries ran.
* Click the session id to see the running queries snapshots associated with each query.

The link between slow queries and running query snapshots is very useful as it allows you to identify exactly why a query was slow.

Hope this helps,

David

**Comment by clhambrick** [comment]
Thank you for the help.  I will look into this below.

Main Street DBAs
Corey Hambrick, Senior Database Administrator
Cell: 859-433-7482
24/7 Call Center - 1-877-682-5300 (option 2)

Email: ***@***.******@***.***>
