### ISSUE TITLE
Test summary links in grouped view

### ISSUE THREAD

**Issue by dv2287** [trimble-oss/dba-dash#759]
Hi,

I recommend improving the behavior of Test summary view when using custom tags to group instances. For instance, a custom tag for environment can be created (dev, test, prod) . When you select the production environment, the test summary will be displayed for instances assigned with the prod tag. Clicking any of the instance count links will display the corresponding instances from the selected group. When you click the View link, it will display the details of the selected test for each instance. However, clicking the link of the Test you're interested in will display its detailed results for all instances (root level). It would be more intuitive if selecting the Test link in grouped view would return detailed results of the selected group. 

Version 2.49.1.0 (and issue was also present in earlier versions)

Best regards

**Comment by DavidWiseman** [comment]
Thanks for the suggestion - I agree the current behavior isn't ideal.  It navigates you up a level because there are no corresponding Checks, HA/DR, Storage nodes etc at the tag grouping level.  Duplicating these at the tag group level might be an option.  I'll consider improving this in a future release.

Thanks

**Comment by DavidWiseman** [comment]
[Included in 3.1](https://dbadash.com/blog/whats-new-in-3.1/) 🎉

**Comment by dv2287** [comment]
Hi David,
after implementing new feature from this issue, I noticed that Group\Show Counts option counts all items in group, including both - instances and DBA Dash nodes / categories. For example, group with 4 instances shows count 9. It is also noticable when you search for single instance - DBA Dash will filter view to corresponding group and instance, but it will display that group contains 6 members.
Additionally, I was a bit confused when looking for jobs timeline, but finally realized that Job Stats and Timeline are available only at the instance level view and not at the group level or root level. If it is not too complicated maybe these two tabs from Jobs category can be removed from group level dispay, the same way as it is removed from the root level.
Finally, after upgrading to version 3.1 I was getting some errors and information messages when clicking the test links from the Test summary view at the group level. This was present for the first few application runs after ugrade and now everything works fine and I cannot reproduce this behaviour anymore. Unfortunately I haven't captured errors and messages.

Best regards.

**Comment by DavidWiseman** [comment]
Hi, I've fixed the counts and removed the timeline and job stats tabs at group level.  Thanks for reporting these bugs - the fixes will be in the next release.  

If you get any more errors when clicking the test links, take a screenshot and log an issue - I will investigate.  Thanks.
