### ISSUE TITLE
Feature request: trigger from UI start snapshot report

### ISSUE THREAD

**Issue by acappelletti** [trimble-oss/dba-dash#774]
HI David,

I'm loading several reports so that I can check everything from the interface... sometimes it would be convenient to force the execution... of some reports without waiting for the scheduling.

It would be handy to have a "right click" run now.... without having to restart the service.
ALEN

**Comment by DavidWiseman** [comment]
Thanks for the suggestion - I agree.  There are some complexities associated with implementing this.  It will probably get included at some point but it might not be soon.

More info:
The GUI doesn't directly connect to any of the monitored instances and currently has no way to talk to the service to trigger the collection.  The DBA Dash design also means that some instances might be sending data to the repository database indirectly via a S3 bucket.  The DBA Dash configuration can be simple with 1 service or there can be many services handling the collections and some without direct connectivity to the repository database.  Some services might also send data to more than 1 repository database.

I've thought about doing this and I think it's possible - just not easy.  e.g. The GUI and the service could communicate via the repository database.  Messages could also be relayed to remote services via the S3 bucket or a SQS queue.  

Thanks,

David

**Comment by acappelletti** [comment]
Thanks for explain me... 
It's great anyway... don't worry...
you're right could be very complicate...seems like a API remote call to a service...
but simple is better... don't complicate it.... stable is better and lightweight.
: )

But a sort of... filter with a text input on TOP every column, do you find it complicated to implement? 

In another company I used a custom windows app where the programmers have inserted the filters as the first row of the data grid and it was really useful... for example in one of the reports that I loaded I would like  only to filter on a single DB... since I it returned 300 rows... ok there is sorting... but it is not the same... to reduce the visual impact could be a good add.

![image](https://github.com/trimble-oss/dba-dash/assets/43847440/9b69199c-6db0-4f2e-b862-9c2c6cc458ac)


Have a nice day, ALEN

**Comment by acappelletti** [comment]
Thanks David for your tip...
I will certainly read those passages carefully.. and if necessary ask here in the forum
ALEN

**Comment by DavidWiseman** [comment]
I'm adding filtering functionality via a context menu.
![image](https://github.com/trimble-oss/dba-dash/assets/33157668/5cb68b5e-b15e-4a99-b4ec-111ba138116f)

**Comment by acappelletti** [comment]
OK perfect....I0m curios to try... but is it already present in version 2.5.1 that I'm downloading? Or in the future?
Thanks David

**Comment by DavidWiseman** [comment]
It will be included in the next release.  The coding is complete for it.

**Comment by DavidWiseman** [comment]
Included in 2.52.0 🚀
