### ISSUE TITLE
Instance_Del  -  Foreign Key violation

### ISSUE THREAD

**Issue by smschissler** [trimble-oss/dba-dash#777]
DBADash Version: 2.49.0.0

When running:

EXEC dbo.Instance_Del @InstanceID = 1, @HardDelete = 1

When there are records in the dbo.IdentityColumns table or the dbo.IdentityColumnsHistory tables for that InstanceID, the following foreign key violations will be generated.

Msg 547, Level 16, State 0, Procedure dbo.Instance_Del, Line 414 [Batch Start Line 2]
The DELETE statement conflicted with the REFERENCE constraint "FK__IdentityC__Datab__1E3A7A34". The conflict occurred in database "DBADashDB", table "dbo.IdentityColumns", column 'DatabaseID'.

Msg 547, Level 16, State 0, Procedure dbo.Instance_Del, Line 418 [Batch Start Line 2]
The DELETE statement conflicted with the REFERENCE constraint "FK__IdentityC__Datab__2022C2A6". The conflict occurred in database "DBADashDB", table "dbo.IdentityColumnsHistory", column 'DatabaseID'.

The following delete commands: 
	DELETE dbo.IdentityColumnsHistory
	WHERE InstanceID = @InstanceID

	DELETE dbo.IdentityColumns
	WHERE InstanceID = @InstanceID

need to be added prior to:

	DELETE dbo.Databases 
	WHERE InstanceID = @InstanceID

Cheers,
Stephen Schissler

**Comment by DavidWiseman** [comment]
Thanks for reporting this issue!  If you are interested in contributing, you could create a pull request to fix this issue.  If not I'll probably take a look at it next week.  Either way thanks for the detailed report and fix. 😊

**Comment by smschissler** [comment]
Sure, I'm new to the GIT process.  I'll do a pull request with the change.
Thanks for making this application open source.

-Stephen

**Comment by DavidWiseman** [comment]
Thanks.  It's worthwhile learning Git as pretty much all software development relies on it now. It's also useful for DBAs that support those development teams.  If you need help, let me know.

I'll also look at adding a test to the GitHub actions to hopefully prevent it from getting broken in the future.  #780

**Comment by DavidWiseman** [comment]
Hi, let me know if you are still interested in doing a PR for this.  If not, I'm happy to do it.  I've created a test for it that should prevent it getting broken again in future.

**Comment by smschissler** [comment]
Hi David,

I have not had time to look into how to do the pull request, so you should
probably do it.

Thanks!
Stephen

**Comment by DavidWiseman** [comment]
No problem.  The fix will be included in the next release.

**Comment by DavidWiseman** [comment]
This is included in version 3.0.  Note, that there is an upgrade to .NET 8.  🚀
