### ISSUE TITLE
Enhancement - Add Options To CPU Performance Graph

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#79]
I like to review Batch Requests/sec, Transactions/sec, Session Count & Worker Thread Count (mostly for Azure SQL DB) when we see high CPU to see if it simply correlates to increased demand or if it is a normal day (or hour) and it's something specific causing the CPU spike.  Would it be feasible to add an options drop down like on the other charts to be able to add these to the CPU graph if you want to see them on a second Y axis?

**Comment by DavidWiseman** [comment]
Hi, thank you for the suggestion.  I think it would be useful to be able to have some more flexibility to pull some data together like this in the same place.  I'll keep this under consideration.  I'd probably look to replace the charting component used by DBA Dash (#35) before doing anything with the charts though.

The Batch Requests/sec counter is available under "Metrics" and you can click the "View" link to see this in a chart.  The other metrics mentioned are not currently captured but it is possible to add your own [custom metrics](https://github.com/trimble-oss/dba-dash/blob/main/Docs/OSPerformanceCounters.md)

Launching a second copy of the application might be a workaround to allow you to see the data at the same time.  I do this occasionally so I thought I would mention it.  Having extra flexibility in the app would be nice though.

**Comment by jacobgexigo** [comment]
Thanks for letting me know about the View link, that is helpful.  I would help contribute to the application, but I don't know the first thing about app development.  :)

**Comment by DavidWiseman** [comment]
Glad it was useful.  I know a lot of people using DBA Dash won't have experience with C#.  There are lots of other ways to contribute to the project.  e.g. Documentation.  Helping to promote the project through blog posts and word of mouth.
Also, some people might be more comfortable improving the SQL code which is all stored procedures located in a SSDT project:
https://github.com/trimble-oss/dba-dash/tree/main/DBADashDB
Or the collection SQL used by the agent is all located here:
https://github.com/trimble-oss/dba-dash/tree/main/DBADash/SQL

I need to provide some instructions for contributing to DBA Dash (#69 )

I'm happy for people to add suggestions to help improve DBA Dash.  I won't be able to implement all suggestions that come in - I will prioritize and work on ones that are useful to me/Trimble.  Other people might also pick up issues that come in as the community around this project grows.

**Comment by coreyhambrick** [comment]
@DavidWiseman I am having an issue with charting and rather than starting a new ticket I thought I would just add to this conversation but will certainly open a new ticket if I need to.  So I just installed DBA Dash on jumpbox server to monitor some development servers.  Been running for say 18 hours.  When I go to the CPU Performance graph, I cannot get any to show when I set the filter above 30 mins.   Maybe the system needs to run for over 24 hours before it will show but if you look at my screenshot if it came through when I switch to 1 hour, all the times below the snippet I took show 0:00 for the hour
![graph](https://user-images.githubusercontent.com/50051547/165961140-772c0c86-845e-44ad-a54d-acf2124fd84f.png)

**Comment by coreyhambrick** [comment]
Ok.  Thank you. I will check it out.

**Comment by DavidWiseman** [comment]
It's possible to create custom dashboards with the changes introduced in #268 - Available in 2.21.0.  You have Batch Requests/sec & Transactions/sec collected, which you can combine with CPU and save as a custom dashboard in the Metrics tab.  I'm guessing you want either the number of active or available worker threads which isn't available as an os performance counter.  
It's possible to add a [custom counter](https://github.com/trimble-oss/dba-dash/blob/main/Docs/OSPerformanceCounters.md) though and query a dmv like sys.dm_os_schedulers to get this information.
