### ISSUE TITLE
Not able to add new servers

### ISSUE THREAD

**Issue by jigar-patel1** [trimble-oss/dba-dash#839]
I'm using latest version 3.1.0.0. I was able to add 10 SQL servers, but when I try to add more servers using "DBADashServiceConfigTool.exe," I see the config getting updated, but the UI tool is not reading new servers. I even dropped the database and re-deployed it, but still, new servers are not being detected or added. Is there something I'm missing? 

I did not find any uninstall instructions for the tool.

**Comment by DavidWiseman** [comment]
Hi,

If you make any changes to the config, you need to stop/start the service to pick up the changes.  This might explain why the config is updated but you don't see then new instances.  It's also possible that there is a problem connecting to the instances.  If you still have a problem after restarting the service, check the Logs folder and look for errors.

To uninstall, just click the uninstall service button in the service config tool.  The app folder & repository database can then be deleted.

Hope this helps,

David

**Comment by jigar-patel1** [comment]
Hi David, 
Appreciate the input. I have re-downloaded and re-installed application and GUI but I'm still getting back same old servers I added first time. Logs do show the servers I added but checking on "Instances" table on the database and config file are showing completely different servers and data collection.

**Comment by DavidWiseman** [comment]
That's odd.  Check that the repository database you are connecting to is the same as the one set as the destination connection.  Maybe you are connecting to an old repository database from a previous test of DBA Dash?

The server name comes from `SELECT @@SERVERNAME` by default so you might want to run that on the monitored instances and see what is returned.  If the server was renamed, you might need to run sp_dropserver/sp_addserver to fix the name if it doesn't match what you expect. 

You can also set the ConnectionID in the config file - this will override `@@SERVERNAME` as the name of the server.  That could be another thing to check - if you have set a ConnectionID set in the config - that will be used as the name of the server. 
 
The ConnectionID is what is used as the unique name for the instance and it's set to `@@SERVERNAME` if it's not defined in the config.  A friendly name can also be configured in the GUI to display instead of the ConnectionID.

Hope this helps

**Comment by jigar-patel1** [comment]
I'm only using one server to deploy the repository database, and it's not changed. I checked "ServiceConfig.json," which reflected the correct new servers, but when I checked the repository database, it did not show new servers.  But every time, it creates old servers I tested with, and it also re-deploys with old servers I tested with. I'm checking on the table "Instances," and it's reflecting old servers only.

**Comment by DavidWiseman** [comment]
The old servers would still be there if you didn't manually delete the repository database.  The uninstall service just removes the service.  The only place the service stores configuration information about your SQL instances is the **ServiceConfig.json** file.  If the instance isn't listed there there isn't any possibility it would have memory from a previous install.  The collected information would remain in the repository database though and still be there if you didn't drop the database.

Note: In the GUI there is a **Manage Instances** option which you can use to mark instances as deleted so they no longer appear in the GUI. https://dbadash.com/docs/help/faq/#how-do-i-remove-an-instance

For the new servers not been collected the most likely cause is a permissions issue or some issue with the connection string.  If you are using Windows authentication, the service will run as the service user account which will need access to your monitored instances.  If you previously ran by double clicking the exe as a console app, it would have ran as your own user account which might have had access. 

The service account also needs to be able to write to the application folder for logging. If it doesn't have access this might cause confusion as it wouldn't be able to write to the logs folder.  You might see info in the logs folder though if you ran as a console app previously as your own account would have access to write to the logs folder.

You can search the Logs for **[ERR]** to look for errors or the name of the instance.  There should be clues in the logs if there are any issues collecting data from your monitored instances.  If things are healthy you should see something like this:

```
2024-03-02 00:00:07.664 +00:00 [INF] Collect ServerProperties, Databases, SysConfig, Drives, DBFiles, Backups, ServerExtraProperties, DBConfig, Corruption, OSInfo, TraceFlags, DBTuningOptions, AzureDBServiceObjectives, LastGoodCheckDB, CustomChecks, DatabaseMirroring, AzureDBResourceGovernance from instance Lab2022Node1 completed in 315.7 ms <102>
2024-03-02 00:00:08.136 +00:00 [INF] Write to destination LAB2022|DBADashDB from Lab2022Node1 completed in 471.8 ms <102>
```

To limit the amount of noise in the log and focus your troubleshooting efforts, you could try adding 1 server at a time to the config.  Note: Any changes to the config will require a service restart to pick up the new config.

Hope this helps.

**Comment by jigar-patel1** [comment]
Hi @DavidWiseman 

Thank You for the prompt replies on my comments. 

I have performed the following checks. 

1. Uninstalled service 
2. I removed the repository database and local folders. 
3. Restarted server. 
4. The user is a sysadmin on the collection and host servers. 
5. No [ERR] in the logs 
6. Reinstalled latest version 3.2.0.0
7. Upon reinstalling, onboard one of the servers 
8. I noticed it monitoring right server but it's not reporting right instance, somehow, its getting cached data and marks my server as old server name. 
9. Config is correct, and even in log files, I found traces of the correct server, but UI is showing a completely different name of the server. 

How can I check/clear the remaining cache to avoid this issue and only input the right server's name?

**Comment by DavidWiseman** [comment]
You can check what's reported in the repository DB:

```
SELECT InstanceID, -- identity column PK
		ComputerNamePhysicalNetBIOS, -- physical hostname.  Should be the same as Instance unless it's a named instance.
		Instance, -- from @@SERVERNAME.  Might return the wrong server name if the server was renamed
		ConnectionID, -- unique connection ID.  Same as Instance unless ConnectionID is specified in the config
		Alias, -- Optional Alias that can be used to override the name displayed in the GUI
		InstanceDisplayName, -- display name in GUI. computed (isnull([Alias],[ConnectionID])),
		InstanceGroupName -- display name in GUI. Not including the database name for azure DB. computed (case when [EngineEdition]=(5) then [Instance] else isnull([Alias],[ConnectionID]) end),
FROM dbo.Instances
```

If Instance is the wrong name for the server.  Connect to the server using the same connection string and run `SELECT @@SERVERNAME` to check if this is returning the correct name for the server.  If it's not, the server has likely been renamed at some point. 

More info:
The instance name comes from [this query](https://raw.githubusercontent.com/trimble-oss/dba-dash/main/DBADash/SQL/SQLInstance.sql) `@@SERVERNAME AS Instance,`
This becomes the ConnectionID also unless the ConnectionID is specified in the config.  The ConnectionID will be used as the display name in the GUI unless the Alias column has been set in the dbo.Instances table in the repository database.

There isn't any cache.  All config is in the ServiceConfig.json file but changes are only reflected after a service restart.  Information about instances collected previously will still be available in the repository database but can be marked as deleted.  If the repository database has been dropped and re-created, all information about the old instances will be gone. Logs of the old collections might still be in the Logs folder unless that is cleared out.

**Comment by jigar-patel1** [comment]
Thank You ... I'm able to resolve it by using  ConnectionID in the config to make sure its using right instance.

**Comment by DavidWiseman** [comment]
Glad it's solved.  If it's where `@@SERVERNAME` isn't returning the correct name on your SQL instance, it's possible to correct it using sp_addserver/sp_dropserver.  e.g.
https://eitanblumin.com/2018/11/06/how-to-update-servername-to-actual-machine-name/
