### ISSUE TITLE
DBADash GUI query timeout when searching slow queries by text over 14 or more days

### ISSUE THREAD

**Issue by R4PH1** [trimble-oss/dba-dash#846]
Hi David, 
I know this might be an edge case. I read all docs I could find about query timeouts on your site and I understand the default, also for the GUI application, is 30 seconds.
Sometimes to troubleshoot slow queries I need to search by snippets of text and run into a timeout. Especially when searching 14 days or more (unfortunately needed from time to time to compare stats).
I am aware that I can run the stored procedure manually but further analyzing the results is just easier within the GUI.

Would it be possible to raise the query timeout to like 2 minutes for slow query searches >= 14 days or configure it for ourselves as an option within the GUI or some separate configuration file?
I don´t know how much effort this would be to implement but this certainly would help a lot. 

Thanks in advance for your efforts.

**Comment by DavidWiseman** [comment]
Hi,

It looks like I need to add this to the docs, but you can configure the default timeout for the GUI using:

```sql
DELETE dbo.Settings WHERE SettingName='GUIDefaultCommandTimeout'
INSERT INTO dbo.Settings
(
    SettingName,
    SettingValue
)
VALUES
(   'GUIDefaultCommandTimeout',  
    120
    )
```

Hope this helps,

David

**Comment by DavidWiseman** [comment]
[Docs updated](https://dbadash.com/docs/help/query-timeout/#gui-timeouts)

**Comment by R4PH1** [comment]
Thanks a lot! I´ll play around with some values to figure out what works best for our use case.
