### ISSUE TITLE
Sort Grid in Configuration Tool

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#856]
When we have a lot of configured connections, it would be nice to be able to sort the grid by any of the columns, especially if we are giving custom Connection ID names and they may start with something that is alphabetized.  For instance, if I were trying to look for a specific connection to delete, it takes a while to scan them by eye, where if we could sort them, it would be fast and easy.

**Comment by DavidWiseman** [comment]
That should be easy to implement - I'll take a look when I get time. 

If you are looking for a collection to delete you can use the search textbox in the bottom right to filter the grid.  It doesn't look like it's searches on the Connection ID though - it probably should so I'll look at changing it also.

**Comment by DavidWiseman** [comment]
Sorting on connection string & connection ID will be included in the next release.  Also filtering on connection ID.

**Comment by DavidWiseman** [comment]
This is included in 3.4 🚀
