### ISSUE TITLE
Issue Upgrading from 3.3 to 3.4

### ISSUE THREAD

**Issue by TheAccidentalDBA** [trimble-oss/dba-dash#874]
![image](https://github.com/trimble-oss/dba-dash/assets/71884153/e34b57ae-06d6-4c23-8436-44fab551b1e6)

**Comment by TheAccidentalDBA** [comment]
As the error stated (and I did not read it completely before posting) I had a custom view that caused this error.  I removed the view and it deployed properly.

**Comment by DavidWiseman** [comment]
Glad you sorted it.  I think the issue was occurring because of a recent change to the Instances table to change LastMemoryDump from DATETIME to DATETIMEOFFSET.  This was to fix #855.

Dropping and re-creating ***_BOCC_SlowQueries_Today*** was the best course of action.

David
