### ISSUE TITLE
dbadashconfig.exe closes silently if .net 6 not installed

### ISSUE THREAD

**Issue by vcmcstech** [trimble-oss/dba-dash#89]
i was told it would detect .net framework missing and prompt me to install it.  It closes silently when I tried.  v 2.13.3

windows event viewer

Description: A .NET application failed.
Application: DBADashConfig.exe
Path: C:\Users\administrator.MK\Downloads\DBADash_2.13.3\DBADashConfig.exe
Message: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      2.2.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64

**Comment by DavidWiseman** [comment]
The prompt to install the .NET framework is generated from Microsoft code.  It's possible this has some dependencies of its own and might not be able to run in some situations.  What version of Windows are you running?

There might be some things I could consider like packaging the application with an installer to improve the user experience.

**Comment by vcmcstech** [comment]
Microsoft Windows Server 2016 Standard Evaluation

**Comment by vcmcstech** [comment]
I think i was using the wrong exe though.  Note the word service is missing from the filename here.  I tried to open the first exe in the file list with Config in the name. 

Later i found dbadashserviceconfig.exe worked ok.  I might have installed .net 6 by that point tho.
