### ISSUE TITLE
Chart Error - Could not obtain information about Windows NT group/user ...

### ISSUE THREAD

**Issue by vcmcstech** [trimble-oss/dba-dash#93]
Logged into DBADash Client on workstation with a domain user with local admin rights
DBADash Service setup to run on the workstation using a separate service account for DBADash
Workstation runs SQL Express for the repository database
One Source Server runs on a different domain.  Another is the local instance on the workstation

DBADash Client throws the error below when opening Performance tab for either Source server.  User in the error is redacted and references the local admin logged in on the workstation.

![dba dash remote server perf tab access error Screenshot 2022-03-20 094849](https://user-images.githubusercontent.com/35636722/159174839-e4d4f988-a81d-4c84-91e2-9aa7a9739e4a.png)

I'm able to view data collected on other tabs ok.

**Comment by vcmcstech** [comment]
Workstation is domain joined but not connected to corporate network.  Unable to connect to domain controller.

Error does not happen if I connect to the corporate vpn.  This allows dbadash to connect to the domain controller.

**Comment by DavidWiseman** [comment]
Hi, I think this error is related to #78.  I believe this is related to the use of WITH EXECUTE AS OWNER which isn't required.  A fix is in to remove this #84.  Removing WITH EXECUTE AS OWNER from dbo.ObjectExecutionStats_Get.

**Comment by vcmcstech** [comment]
Confirmed.  Removing with execute as owner from the sproc avoids the error.

**Comment by DavidWiseman** [comment]
That's great - thank you for letting me know.
