### ISSUE TITLE
The type initializer for 'DBADashGUI.Config' threw an exception

### ISSUE THREAD

**Issue by nevets429** [trimble-oss/dba-dash#931]
Have DBADash running fine on our server and gathering data from our SQL servers and the GUI works fine on the server but when we try to run from our workstations, we get a messagebox saying "The type initializer for 'DBADashGUI.Config' thre an exception" at launch.  The GUI does start after clearing the message box but anytime you try to connect to the database, it comes back again.  Initially was happening on v3.6, we updated the database and server to 3.7.0 this morning hoping it would resolve the issue but still getting the same error.   This is happening on both Windows 10 and Windows 11 client machines.

**Comment by DavidWiseman** [comment]
This is a bit odd.  I think [this](https://github.com/trimble-oss/dba-dash/blob/main/DBADashGUI/Config.cs) is the section of code it will be having problems with.  I can reproduce the error if I **delete** the Settings_Get stored procedure.  Some other error in the process would also result in the same error - connection issue, timeout or permissions issue but these don't seem likely.  I've tried setting bad values for some settings but the code is using TryParse and it just results in the defaults being used.

You could try running Settings_Get with the same user that's having the issues to see what happens.  I can probably add some error handling for the next version to catch the underlying error

**Comment by nevets429** [comment]
I'll grab the source code and step through it, thought maybe someone had seen it before.

**Comment by nevets429** [comment]
Issue resolved.  It was permissions on the SQL side causing the issue, the group the users are in had access to the tables but couldn't see any of the stored procedures.

**Comment by DavidWiseman** [comment]
Great - glad you got it sorted.  The App or AppReadOnly roles can grant access to the GUI.  I'm going to fix the app anyway so we get a more useful error message.  It will show this error instead in the next version:

![image](https://github.com/trimble-oss/dba-dash/assets/33157668/058ab621-883f-476c-ac23-e5f5f5507a00)
