### ISSUE TITLE
Bug Report: WMI Connection Issue in DBA Dash with FQDN

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#934]
**Description:**
When attempting to connect to the server via WMI in the DBA Dash application, the connection fails when using the short server name (e.g., server1). The connection is only going to be successful when using the fully qualified domain name (FQDN) (e.g., server1.shshs.hshshs) but DBA dash is not using it unfortunately.

This happens because it is assuming the server is in the same domain I think. When you can have multiple  

Fyi super love the product

**Comment by Drakokorian** [comment]
same issue on 3.7

**Comment by DavidWiseman** [comment]
DBA Dash uses the value from `SELECT SERVERPROPERTY('ComputerNamePhysicalNetBIOS')` to connect.  There doesn't seem to be a good wat to get the FQDN from SQL apart from trying to read it from the registry.  There is a `DEFAULT_DOMAIN()` function that returns the netbios domain name - but this doesn't seem to be documented as far as I can tell.

Even if I was able to swap to use the FQDN, I'm not sure if it would work, as [a few things](https://dbadash.com/docs/help/wmi/) need to be in place for WMI to work.  To get around the name resolution issue you can create an entry in the hosts file of the computer where DBA Dash runs if it has a static IP.  Or a host A in DNS.

For multiple domains, I'd suggest a different workaround. Deploy another DBA Dash service so you have one running in the local domain.  They can both push the data to the same repository database.

Hope this helps

**Comment by Drakokorian** [comment]
So I have tried the following to get the domain name 

DECLARE @domain NVARCHAR(256);

-- Query the domain name from the registry
DECLARE @RegQueryCmd NVARCHAR(4000);
SET @RegQueryCmd = 'DECLARE @DomainName NVARCHAR(256); ' +
                   'EXEC master.dbo.xp_instance_regread ' +
                   '''HKEY_LOCAL_MACHINE'', ' +
                   '''SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'', ' +
                   '''Domain'', ' +
                   '@DomainName OUTPUT; ' +
                   'SELECT @DomainName AS DomainName;';

-- Execute dynamic SQL to retrieve domain name
EXEC sp_executesql @RegQueryCmd, N'@DomainName NVARCHAR(256) OUTPUT', @domain OUTPUT;

-- Output the domain name
SELECT @domain AS DomainName;


I will test both of these option on monday for the other two

**Comment by DavidWiseman** [comment]
The registry option works to get the domain but requires the user to be sysadmin.  It's also an undocumented procedure.  Using `DEFAULT_DOMAIN()` is probably a better option (If DOMAIN\SERVERNAME format works) as it doesn't require sysadmin - but also appears to be undocumented.  

Editing the hosts file might be a good solution if it works or it might highlight other issues running WMI across domains.  

PS.  If you just want to avoid the WMI errors, there is a No WMI checkbox that can be used to disable WMI collections.  There is only a [limited](https://dbadash.com/docs/help/wmi/#what-data-is-collected-with-wmi) amount of data collected via WMI.

**Comment by Drakokorian** [comment]
I say close the following I will have to see about a workaround with custom collections, the reasons is it is missing information without it :)
