### ISSUE TITLE
Bulk Import Servers to Monitor via Text File in DBAdash Config

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#935]
I would like to request the addition of a feature in DBA Dash that allows users to bulk import servers to monitor using a text file. This feature will greatly enhance efficiency and ease of use for administrators managing a large number of servers.

Use Case:
Currently, adding servers to monitor in DBA Dash is a manual process, which can be time-consuming and prone to errors, especially when dealing with a large number of servers. By enabling bulk import via a text file, users can quickly and accurately add multiple servers in one action. Currently adding over 800 servers.

**Comment by DavidWiseman** [comment]
Hi, there are already a couple of options for this.  In the service config tool, you can paste in a list of servers in the Source textbox.  Enter each server on a new line.

Connections can also be [added via the CLI](https://dbadash.com/docs/setup/cli-install/#add-source-connection)

Hope this helps

**Comment by Drakokorian** [comment]
sound I missed that
