### ISSUE TITLE
Marking an instance hidden in manage instances. 

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#938]
When other users other than me try to mark an instance hidden they do not see the 
![error bug ](https://github.com/trimble-oss/dba-dash/assets/175303303/ffa53ce4-aea5-4556-a1ce-02a6c6e6b997)
checkbox for marking them hidden just a bank screen

**Comment by DavidWiseman** [comment]
That's odd - I don't have a good explanation for this issue.  If you log in to the same computer where it's not working does it work for you there - just trying to narrow it down to an issue with computer or user.  Do checkboxes display OK in other locations for the user.  e.g. Select Columns
![image](https://github.com/trimble-oss/dba-dash/assets/33157668/231cd7db-7cdf-4022-90fd-91ca2e833531)

**Comment by Drakokorian** [comment]
Yes so we are using the same server, he has tried testing on his laptop and on the server still the same. 

Just happens on manage instances tab at the moment for him.

**Comment by DavidWiseman** [comment]
Thanks for confirming.

**Comment by DavidWiseman** [comment]
This may be occurring because the row height is too small.  If I re-size the row to be smaller I can re-produce this behaviour. 
![image](https://github.com/user-attachments/assets/001b4f24-d01a-48d2-b054-de9ebeb09988)

If this issue still occurs, resize the row to make it taller.  Let me know if the checkbox appears.

**Comment by DavidWiseman** [comment]
Hi, I've increased the row size, which should resolve the issue.  If you want to test it:

* Install 3.9.1 if it's not already installed.
* Replace the 2 binary files from the zip below.

[DBADash_3_9_1_ManageInstancesPatch.zip](https://github.com/user-attachments/files/16970265/DBADash_3_9_1_ManageInstancesPatch.zip)

Thanks

**Comment by Drakokorian** [comment]
Tested deployed and works on 3.9.1 thank you.On 11 Sept 2024 21:50, David Wiseman ***@***.***> wrote:
Hi, I've increased the row size, which should resolve the issue.  If you want to test it:
Install 3.9.1 if it's not already installed.Replace the 2 binary files from the zip below.
DBADash_3_9_1_ManageInstancesPatch.zip
Thanks

**Comment by DavidWiseman** [comment]
Thanks for confirming.  This fix will be included in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 3.10 🚀
