### ISSUE TITLE
Copy button does nothing

### ISSUE THREAD

**Issue by vcmcstech** [trimble-oss/dba-dash#94]
So far all forms I tried, the copy button does nothing.  Selecting a cell and pressing ctrl+c does copy the data though.

2.13.3

**Comment by DavidWiseman** [comment]
Hi, the copy option is to copy the entire grid as HTML.  This will paste into a program like Excel or Word.  The application would need to support pasting HTML content from the clipboard so it might not work in all applications.  Which tab were you copying from and which application are you pasting to?

**Comment by vcmcstech** [comment]
many tabs, assume all

pasting to text editor.   same happens pasting to notepad.

works ok for me if pasting to word or excel though.

**Comment by DavidWiseman** [comment]
A fix for this will be in the next release.  The data will be copied to the clipboard as text in addition to HTML.  The data pasted into notepad would be the HTML text.  You could then save this as a *.html file.

**Comment by DavidWiseman** [comment]
This issue is fixed in the latest release now.
