### ISSUE TITLE
SQL error executing DBFileSnapshot_Get

### ISSUE THREAD

**Issue by dbloke** [trimble-oss/dba-dash#940]
Hi,
We are complementing DBADash using Grafana.
Getting T-SQL error when executing dbo.DBFileSnapshot_Get using @InstanceID parameter:

Must declare the scalar variable @InstanceID

I can see from the proc that the sp_executesql statement is not passing it in to the dynamic sql.

**Comment by DavidWiseman** [comment]
Hi, you are right it's not passing it in to the dynamic SQL.  It's probably just passing in InstanceGroupName instead from the app side (to work for Azure DB which is a collection of instances) - so we don't see the bug in the app.

If you like you could submit a PR to fix the [DBFileSnapshot_Get](https://github.com/trimble-oss/dba-dash/blob/main/DBADashDB/dbo/Stored%20Procedures/DBFileSnapshot_Get.sql) proc.  If you don't want to that's OK - I'm happy to do it.  It's a quick fix for me to apply.

**Comment by dbloke** [comment]
I'll let you fix at your convenience. I have a work around for now. We already have a few bespoke procs, Grafana can't handle variant datatypes at all!

**Comment by DavidWiseman** [comment]
It will be fixed in the next version.  The new version is available here if you wanted to apply it sooner.
 [DBFileSnapshot_Get](https://github.com/trimble-oss/dba-dash/blob/main/DBADashDB/dbo/Stored%20Procedures/DBFileSnapshot_Get.sql)

**Comment by DavidWiseman** [comment]
Included in the latest release. 🎉
