### ISSUE TITLE
What do I increase it too 

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#945]
Do I increase to 3 or do I go to like -3 the documentation is not clear 
https://dbadash.com/docs/help/faq/
Increase the ServiceThreads value in the ServiceConfig.json file to allow the DBA Dash agent to work with a larger number of instances.
{
  "ServiceThreads": -1,
  "LogInternalPerformanceCounters": false,
  "CollectionSchedules": {
    "Databases": {
      "Schedule": "0 0/10 * ? * * *",
      "RunOnServiceStart": true
    },

**Comment by DavidWiseman** [comment]
You need to set it to a positive number equal to the number of threads you want to use.  If it's set to -1 or any number less than or equal to zero, the number of threads will be set to 10.  The actual number of threads is logged in the log file when the service starts:

`2024-07-21 12:48:48.738 +01:00 [INF] Threads 10 (default) <10>`

So if you set it to 3, this is a reduction from the default thread count.  If you set it to -3 nothing will change.

Note: The default may change in the future.

Hope this helps.  I'll close the case but if you need more help, reply back.

**Comment by DavidWiseman** [comment]
PS.  I've also updated the documentation:
![image](https://github.com/user-attachments/assets/a6edb3c8-6814-4a6a-9405-f5a5d7e6c4f4)
