### ISSUE TITLE
Create Exception for Checks when SQL Server Agent is not running

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#950]
Dont see an option to create exception for servers that the Agent Service has been turned off intentionally.

**Comment by DavidWiseman** [comment]
There isn't an option for this but I'll consider adding it.

**Comment by DavidWiseman** [comment]
This will be included in the *next* version.  There is an extra checkbox in the Agent Job Thresholds dialog to disable the check.

![image](https://github.com/user-attachments/assets/b1fd1a4f-fa08-4bc9-9780-4df028b664e2)

**Comment by DavidWiseman** [comment]
Included in 3.9 🚀
