### ISSUE TITLE
Changing the Slow threshhold query capture 

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#951]
We have changed the Slow query threshold to 5000 ms on 400 servers however it is still capturing data greator than 1000ms. 

Is there a time delay or do I need to disable persist before making changes?

**Comment by DavidWiseman** [comment]
Any changes made to the config will require a restart of the service to pick up the changes.

**Comment by Drakokorian** [comment]
yeap we have done that one 3 times lol still capturing under 5 milliseconds

**Comment by DavidWiseman** [comment]
Do you have the **Persist XE Sessions** checked?  If this option is checked, the event session doesn't get dropped/re-created.  This allows you to apply any custom filtering you want to the event session but it will also mean that any changes to the slow query threshold setting won't be applied (unless the session is dropped manually).

**Comment by Drakokorian** [comment]
Hey David,

Please feel free to close this issue as the update has now been propagated across all servers. However, we have identified a bug in the latest SQL Server 2016 where the Extended Events (XE) are growing to enormous sizes. This issue appears to be related to the memory leak problem documented in SQL Server 2012, which is described in the following link: https://support.microsoft.com/en-us/topic/kb2965758-fix-memory-leak-occurs-when-you-start-and-stop-an-xevent-session-repeatedly-in-sql-server-2012-f8fe67e2-c5fc-a279-7296-da8349b0c6ea.

There does not seem to be a fix available in any of the latest cumulative updates (CU) for SQL Server 2016.

Thank you.

**Comment by DavidWiseman** [comment]
I had slow query capture disabled in my lab on my SQL 2016 SP3 instance.  I've re-enabled it and will see if the memory clerk grows in size.  I might not see anything though as I don't really have a lot of activity in my lab.  DBA Dash does start/stop the event session as a way to flush the captured events so they don't need to be re-processed on the next collection.

Mainstream support ended for SQL 2016 in 2021 so if the bug exists in the latest version it's unlikely to get patched.  It's still under extended support but this is just for security patches if you have a subscription.  If you can it might be worth planning an upgrade to SQL 2022 which has mainstream support until 2028.  Mainstream support for 2019 ends early next year.

There are a variety of reasons people are stuck on older versions of SQL Server.  I plan to support old versions in DBA Dash as long as it remains practical and the effort is relatively low. SQL 2005 is the oldest version that works with DBA Dash.
