### ISSUE TITLE
Another Instance_Del FK violation

### ISSUE THREAD

**Issue by dbloke** [trimble-oss/dba-dash#957]
Msg 547, Level 16, State 0, Procedure dbo.Instance_Del, Line 435 [Batch Start Line 24]
The DELETE statement conflicted with the REFERENCE constraint "FK_RunningJobs_Instances". The conflict occurred in database "DBADashDB", table "dbo.RunningJobs", column 'InstanceID'.

We have a largish SQL estate (450+) with many different versions of SQL (2008R2 - 2022)

Occurred on an unpatched 2008R2 that would get memory dumps and stop the SQL service. Instance has been shut down for good and put out of its misery, but managed to leave behind a zombie row in the RunningJobs table!

Hope you don't mind us putting DBA Dash through its paces!

**Comment by DavidWiseman** [comment]
Hi,

I have a PR that will fix this issue.  If you want to try it out, you can replace the Instance_Del stored proc with [this one](https://raw.githubusercontent.com/trimble-oss/dba-dash/2a55470f82b5a1201a68816d4de3a3ef29cb57a2/DBADashDB/dbo/Stored%20Procedures/Instance_Del.sql) from the pull request. #959 

Thanks for reporting this,

David

**Comment by dbloke** [comment]
Perfect, did the job. Thanks for the update.

**Comment by DavidWiseman** [comment]
Great.  Thanks for letting me know.  The fix will be included in the next release.

**Comment by DavidWiseman** [comment]
Included in 3.8.0 🎉
