### ISSUE TITLE
Feature Request: Connection Status Column for dbdash Config Source Screen

### ISSUE THREAD

**Issue by Drakokorian** [trimble-oss/dba-dash#960]
Objective:
Enhance the user experience on the dbdash Config Source screen by simplifying the process of managing and removing existing connections.

Current Situation:
The existing connection table does not provide a clear indication of whether a connection is currently active or inactive. This makes it challenging for users to efficiently clean up or remove connections.

Proposed Feature:
Add a new column to the existing connection table that displays the connection status. This column should indicate whether a connection is active or inactive using either:

A numerical status (1 for connected, 0 for disconnected)
Color-coded indicators (green for connected, red for disconnected)
Benefits:

Improved Usability: Users can quickly identify active and inactive connections, making it easier to manage them.
Efficiency: Streamlines the process of cleaning up unused or inactive connections, saving time and reducing clutter.
Visual Clarity: The use of color coding or numerical indicators provides immediate, at-a-glance information about connection status.
Implementation Details:

Column Addition: Introduce a new column labeled "Status" in the connection table.
Status Indicators:
Numerical: Use 1 to denote an active connection and 0 to denote an inactive connection.
Color-coded: Use a green icon or cell background to represent active connections and a red icon or cell background to represent inactive connections.

obviously feel free to ignore, it is just me as I am coming across items that would make life a bit easier

**Comment by DavidWiseman** [comment]
Thanks for the suggestion - I might consider doing something along these lines.  From the config we have no way of knowing if a connection is active or not.  It would be possible to:

* Open a connection to each source connection and display a list of connections that couldn't be contacted at this point in time.  In some cases the connection failure might be temporary (reboot etc).  Sometimes the current user might not have access if Windows auth is used but the service might be able to connect OK (or vice versa).  
Note: This check could be done in parallel, but it will be slow if we need to wait for connections to timeout.
* We could check against the repository database and show the last collection date.  This might be a better option but in some situations we might be pushing data to a S3 bucket and not have direct access to the repository database.  It will probably work for most people though.

Workaround:
You can identify an instance that is inaccessible in the GUI based on the collection dates.  You can paste the name into the config tool to find it quickly in the config.   Delete it from the config then mark it deleted in the GUI.  
This isn't ideal if you have a large number of connections.  I'd would like to improve this and it would be beneficial for us (Trimble) also.

**Comment by Drakokorian** [comment]
Option 2 would not work if it never connected to the repository database which is the catch. Maybe include a check to see which connections are not currently in the repository database

**Comment by DavidWiseman** [comment]
This will be included in the next release
![image](https://github.com/user-attachments/assets/d30273f0-cfa3-42ce-93dc-3c33a3bf2335)

**Comment by Drakokorian** [comment]
Legend Perfect, I will deploy this tomorrow.  feel free to close

**Comment by DavidWiseman** [comment]
Included in 3.8.0 🎉
