### ISSUE TITLE
Feature Request: Select Server Names from the GUI

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#977]
Please add the ability to select and copy server name or names from GUI by highlighting them.

**Comment by DavidWiseman** [comment]
Do you mean copying the server names from the tree?
![image](https://github.com/user-attachments/assets/fa313046-c11f-4466-a205-b76cd773d6c6)

It appears that ctrl+c doesn't work by default.  I might be able to get this to work or add the feature via a context menu.  As a workaround, ctrl+c will work from the grid - the performance summary tab will display the server name.

Is this to make it easier to connect to the server via SSMS - to paste in the connection dialog or something?

**Comment by aachaemenes** [comment]
No, I was talking about the check report and other reports. I cant select those servers in the report and copy and paste the names or name. I know I can use excel report feature which is great but it is much faster to grab the server names quickly by highlighting them and use ctrl C and ctrl V.

**Comment by DavidWiseman** [comment]
Copy/Paste using Ctrl+C, Ctrl+V works from the grid.  Select the cell or cells you want to copy and use Ctrl+C.  I've verified this works on the Summary tab and it should work everywhere else as this is built into the DataGridView control.  
![image](https://github.com/user-attachments/assets/84a9d2ef-a3c3-479b-8180-1c03c818c6da)

If it's not working somewhere let me know where.  If it's not working everywhere - copy/paste might not work in some cases over a RDP session.  Check that copy/paste is working from other apps.

**Comment by aachaemenes** [comment]
problem is the instance name column. let say i select a server name and want to copy and paste it to SSMS, i have to paste it into a notepad then remove the instance name header and grab the server name .

**Comment by DavidWiseman** [comment]
Which tab are you trying to copy/paste from?  In most cases the header text isn't included but there does seem to be some places where it is included.

**Comment by DavidWiseman** [comment]
Header text should no longer be included in 3.10 🚀
