### ISSUE TITLE
DB Config Scope

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#979]
Does DBADASH tracks each DB compatibility Level?

It is important to see if any db is set to have lower compatibility level.

**Comment by DavidWiseman** [comment]
In the Configuration node, select the DB Options tab.  At root level you will see a count of databases with old compatibility level in the "Old Compat Level" column.  If you drill down you will see all the database-level information including the compatibility level of each database.

![image](https://github.com/user-attachments/assets/86180f27-1875-4350-97ad-0b83c7a06678)


![image](https://github.com/user-attachments/assets/d16b691f-84cd-44ad-a09b-0cde05cd7532)

Hope this helps

**Comment by aachaemenes** [comment]
i was talking about db configuration tab where you have listed cardinality and maxdop for all the dbs for all the instances. very easy to pull a report vs click on each instance and pull a report that way. you have 6 metrics there, I think compatibility level is pretty important to be there too.

**Comment by DavidWiseman** [comment]
The DB Configuration tab shows [database scoped configuration](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver16) settings.  It's filtered to show configured settings by default - with the filter removed, you will see a larger number of columns.  The compatibility level doesn't fit here as the report is a pivot on the DB scoped configuration which doesn't include compatibility level.  

The DB options tab might be able to provide what you need.  At root level, you can click the **Detail** button which will give you the compatibility level for databases across all your instances - so you don't need to drill down for each instance.  

A [custom report](https://dbadash.com/docs/how-to/create-custom-reports/) is another option.  This will give you a starting point that you can customize or use as is:

```
/*
	Database Compatibility Level
	

	Custom report for DBA Dash.
	http://dbadash.com
	Generated: 2024-09-02 21:20:43 
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER   PROC [UserReport].[DatabaseCompatLevel](
	@InstanceIDs IDs READONLY,
	@OldCompatLevel BIT=NULL
)
AS
SELECT I.InstanceDisplayName AS Instance,
		D.name AS DB,
		D.compatibility_level AS [Compatibility Level],
		I.MaxSupportedCompatibilityLevel AS [Max Supported Compatibility Level],
		calc.[Is Old Compat Level]
FROM dbo.InstanceInfo I
JOIN @InstanceIDs T ON I.InstanceID = T.ID
JOIN dbo.Databases D ON I.InstanceID = D.InstanceID 
OUTER APPLY(SELECT CASE WHEN D.compatibility_level < I.MaxSupportedCompatibilityLevel THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS [Is Old Compat Level]) calc
WHERE I.IsActive=1
AND D.IsActive=1
AND (calc.[Is Old Compat Level] = @OldCompatLevel OR @OldCompatLevel IS NULL)
GO

/* Report customizations in GUI */
DELETE dbo.CustomReport
WHERE SchemaName = 'UserReport'
AND ProcedureName = 'DatabaseCompatLevel'

INSERT INTO dbo.CustomReport(SchemaName,ProcedureName,MetaData)
VALUES('UserReport','DatabaseCompatLevel','{
  "ReportName": "Database Compatibility Level",
  "CustomReportResults": {
    "0": {
      "ColumnAlias": {},
      "CellFormatString": {},
      "DoNotConvertToLocalTimeZone": [],
      "ColumnLayout": [],
      "ResultName": "Result0",
      "LinkColumns": {},
      "CellHighlightingRules": {
        "Compatibility Level": {
          "Rules": [
            {
              "Status": 4,
              "Value1": "false"
            },
            {
              "Status": 2,
              "Value1": "true"
            }
          ],
          "TargetColumn": "Is Old Compat Level"
        }
      }
    }
  }
}')
```

**Comment by aachaemenes** [comment]
You are the man. Thanks.
