### ISSUE TITLE
Enhancement - Instance Grouping

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#98]
We do 3rd party work for a data center where the customers may have servers named the same thing (SQL1, SQL2, etc.).  It would be nice to be able to create groups in the GUI and be able to add instances into them, so they are visually grouped on the left column.  This would be similar to the concept in place for SSMS Registered Servers.  I imagine the Primary Key could be changed to include the group so that the instance would still be unique in the database, etc.

**Comment by DavidWiseman** [comment]
Hi.  At the moment two SQL instances with the name SQL1 would be treated as the same SQL instance.  When the agent collects data from a SQL instance is assigns a "ConnectionID" which is based on the machine name and instance name.  This is used to uniquely identify the instance.  A lookup on the ConnectionID is used to find the InstanceID identity column.

The plan was to have the option to override the connection id value in situations where the machine name was the same. This is something I haven't needed myself and it never got implemented.  The connection id did get used as a quick way to support AzureDB - As each AzureDB needs to be treated more like a SQL Instance than a database.  In this case I automatically add the database name to the connection id.

An option to override the Connection ID might be a way to support collecting from SQL instances that share the same name.  There might also need to be some changes to the GUI to get them to display correctly.  This might not be too big a deal - I'll take a look at when I get chance.

There isn't a way to group connections in the GUI, but there is a tagging feature that could be useful.  You could add a Tag for customer for example and you can use the Tag filter drop down to identify all the servers associated with a customer.  By default there are some system tags created.  If you go to Configuration in the tree under the server - then click the "Tags" tab, you can add custom tags.

It's not high priority for me, but at some point I might add the option to group the tree by a tag which would provide a way to organize the servers.

Thanks

**Comment by alin-selicean** [comment]
Hi. One possible enhancement along the same lines as above...

I just installed DBADash and I am monitoring exclusively RDS instances (and probably Azure SQL Managed Instances in the near future). At least for RDSs, we cannot change the machine names and they show up as EC2AMAZ-whatever-meaningless in the UI. I know about the tags, but these doesn't help. One possible enhancement could be that if a certain tag is present (say PreferredDisplayName or DisplayName etc) to show that in the UI. 

Could this be more easily implemented than the grouping?

**Comment by alin-selicean** [comment]
Thanks.,

**Comment by DavidWiseman** [comment]
The changes discussed in my last comment will make it into the next release.  There is no grouping of instances in the UI but you will be able to set the display name.  Also, the ConnectionID can be configured if you need to support instances with the same name.

**Comment by DavidWiseman** [comment]
Custom instance aliases are included in the latest release

**Comment by jacobgexigo** [comment]
I have updated and it looks to be working well, thank you!  I tried just setting the names in the config tool and updating the visual name in the GUI, but it seems to have kept both the old and new Instance records, so I just dropped the database and redeployed and added the connections back in (not a big deal).

**Comment by DavidWiseman** [comment]
Hi, the ConnectionID which you set in service config tool is used to identify the instance in the repository.  If you change the ConnectionID you will have a new instance appear unless you coordinate an update like this:
* Stop the service
* Update the ConnectionID in the Instances table in the repository DB 
* Update the ConnectionID in the service config tool.

If you didn't want to keep history you could also go to Options\Manage Instances and mark the old instance as deleted.  It's still there to restore if you need to.

I don't think many people will need to use the ConnectionID - it's only really needed if you have conflicting instance names.

**If you just want to change the display name, there is a much easier way:**

* Click Options\Configure Display Name in the GUI.
* Edit the display name as required.

Hope this helps

**Comment by DavidWiseman** [comment]
The option has been added to group instances by tag which will be available in the next release.

**Comment by DavidWiseman** [comment]
Included in 2.25.0 🚀
