### ISSUE TITLE
Feature Request: Identity Column threshold based on Estimated Days.

### ISSUE THREAD

**Issue by chadbaldwin** [trimble-oss/dba-dash#981]
Most of the time I'm checking the Identity Columns tab, I'm usually not worried about the percentages. If a table has been at 88% Used for 6 months, then I'm not as worried about it. But if a table is at 50% but has an "estimated days" value of 90, that's _much_ more concerning even though percentage-wise would be marked as OK.

My main goal with this is that we have a lot of tables that are over the warning and critical thresholds but are fairly stagnant tables. By setting the thresholds based on Estimated Days, that would allow me to clean up the Summary views.

**Comment by DavidWiseman** [comment]
Thanks for the suggestion - that makes sense.  I'll probably include it in a future release.

**Comment by DavidWiseman** [comment]
This will be included in the next release.  You can use a threshold on days and percent and it will alert if either threshold is met.  You can disable the % threshold and just alert on days remaining or vice versa.   The summary page shows max % and min days remaining now

![image](https://github.com/user-attachments/assets/8f737932-ba3d-4091-9997-706cd906f7ab)

![image](https://github.com/user-attachments/assets/0806eb40-f4ee-473e-8450-b32c047ca4a4)

**Comment by DavidWiseman** [comment]
Included in 3.9 🚀
