### ISSUE TITLE
Not displaying Object Execution stats for Azure SQL databases where database_id doesn't match db_id()

### ISSUE THREAD

**Issue by rgrwilloughby** [trimble-oss/dba-dash#994]
Hello
we have an issue where we are not getting object execution stats in the gui for some of our Azure SQL databases. Had a dig and I think its because the database_id when querying sys.databases locally on the database doesn't match db_id() for the databases with the issue. I believe the value returned by db_id() is same as the dmvs return for database_id.

As an aside, db_id(), when queried locally in the application database, does match the database_id from sys,databases in master.

It is documented here
[https://learn.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=azuresqldb-current&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(DB_ID_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(MiscellaneousFilesProject)%3Bk(DevLang-TSQL)%26rd%3Dtrue#remarks](https://learn.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=azuresqldb-current&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(DB_ID_TSQL)%3Bk(sql13.swb.tsqlresults.f1)%3Bk(sql13.swb.tsqlquery.f1)%3Bk(MiscellaneousFilesProject)%3Bk(DevLang-TSQL)%26rd%3Dtrue#remarks)

I did try directly updating database_id in [dbo].[Databases] and it sort of works but then we get another entry in [dbo].[Databases] for the original version so may well cause  issues. 
thanks
Robin

**Comment by DavidWiseman** [comment]
Thank you for reporting this issue - I'll investigate when I get time.

**Comment by DavidWiseman** [comment]
This should be fixed in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 3.10 🚀
